ps2dev/ps2sdk

ee/debug/samples/Makefile.sample, ee/draw/samples/texture/Makefile.sample, ee/erl/samples/cpp-hello/Makefile.sample, ee/erl/samples/hello/Makefile.sample, ee/libvux/src/vuhw.c, ee/packet/src/packet.c, ee/rpc/audsrv/samples/playadpcm/Makefile.sample, ee/rpc/audsrv/samples/playcdda/Makefile.sample, ee/rpc/audsrv/samples/playwav/Makefile.sample, ee/rpc/audsrv/samples/playwav2/Makefile.sample, ee/rpc/audsrv/samples/testcd/Makefile.sample, ee/rpc/multitap/samples/Makefile.sample, ee/rpc/padx/samples/Makefile.sample, samples/Makefile_sample
Get rid of "lvalue required as left operand of assignment" error. Minor fixes.
=> Fixed broken with previous commit samples

ee/kernel/Makefile, ee/kernel/include/kernel.h, ee/kernel/include/syscallnr.h, ee/kernel/src/fileio.c, ee/kernel/src/kernel.S, ee/libc/include/malloc.h, ee/libc/src/alloc.c
This add:
- AddDmacHandler2 function
- check for NULL pointer in fioIoctl
- realloc64 function
https://github.com/belek666/sms
=> Minor changes to support SMS

ee/Rules.make, ee/erl-loader/Makefile, ee/kernel/src/osdsrc/Makefile, ee/kernel/src/tlbsrc/Makefile, iop/Rules.make, samples/Makefile.eeglobal_cpp_sample, samples/Makefile.eeglobal_sample, samples/Makefile.iopglobal_sample
Some more friendly setup for compatibility with modern toolchain. BTW maybe it is possible to port more changes from uyjulians [fork](https://github.com/ps2dev/ps2sdk/compare/master...uyjulian:uyjworking)?
=> Some makefile fixes for proper tool version recognition

ee/kernel/Makefile
=> use bin2c in ps2sdk tools directory

ee/network/tcpip/src/sys_arch.c
The SendMbx function within ps2ip (EE) did not clear the next pointer, causing undefined behaviour.
=> (LWIP-EE) Fixed dangling pointer in SendMbx (next not initialized) & added more comments

iop/iLink/IEEE1394_bd/src/imports.lst, iop/iLink/IEEE1394_bd/src/include/scsi.h, iop/iLink/IEEE1394_bd/src/sbp2_driver.c, iop/iLink/IEEE1394_bd/src/scsi.c, iop/usb/usbmass_bd/src/include/scsi.h, iop/usb/usbmass_bd/src/scsi.c, iop/usb/usbmass_bd/src/usb_mass.c
This fixes write support for both the USB and the iLink block device drivers.
=> Fix write support

ee/font/src/fontx.c, ee/font/src/fsfont.c, iop/system/mtapman/src/freemtap.c, iop/usb/usbd/src/interface.c
This will fix also #91 
I hope that changes in USB function are safe.
I am not really sure if these commits should be squashed or no so I left it to devs.
=> Fixed some warnings captured by modern toolchain

ee/libc/src/time.c
=> Fix time function

tools/adpenc/src/main.c
This is just to write the fileSize of the input file to the output header... useful to determine duration of the compressed adp later on.
=> small update to adpenc

.github/workflows/docker.yml, Dockerfile
This PR dispatch a `run_build` action to `ps2-packer` as well after a successful docker image creation.
Additionally, the git dependency has been removed from `Dockerfile`
Thanks
=> Dispatch build to `ps2-packer`

ee/libc/src/ps2sdkapi.c
Fixes #134. Majority of this code is copied from [fopen()](https://github.com/ps2dev/ps2sdk/blob/ea69e7cf8e4cea516b18dbdee13f698b8f336257/ee/libc/src/stdio.c#L347) prior to the switch to using newlib for libc.
This should work with fileio and fileXio.
=> Use pwd in filename passed to `open()`.

common/include/usbhdfsd-common.h, ee/Rules.release, ee/kernel/src/sifcmd.c, iop/Rules.release, iop/fs/bdm/include/bdm.h, iop/fs/bdmfs_vfat/src/fat_driver.c, iop/fs/bdmfs_vfat/src/fs_driver.c, iop/fs/bdmfs_vfat/src/include/fat_driver.h, iop/iLink/IEEE1394_bd/src/scsi.c, iop/kernel/include/irx.h, iop/kernel/include/loadcore.h, iop/kernel/include/thbase.h, iop/usb/usbhdfsd/src/fat_driver.c, iop/usb/usbhdfsd/src/fs_driver.c, iop/usb/usbhdfsd/src/include/fat_driver.h, iop/usb/usbmass_bd/src/scsi.c, iop/usb/usbmass_bd/src/usb_mass.c
I'm cleaning up all the changes/improvements I've made to my local branches. Please see all separate commits for more information.
One thing to note is that I've reverted #164
=> Multiple small updates/improvements

samples/Makefile.iopglobal_sample
For use in external projects more tweaks are needed
=> Update IOP samples makefile

ee/network/tcpip/include/ps2ip.h, iop/kernel/include/xloadcore.h, iop/kernel/include/xmodload.h, iop/kernel/include/xthbase.h, iop/kernel/include/xtimrman.h
Improvements to header imports, mainly for automated processing of headers.
=> IOP import improvements

iop/kernel/include/ctype.h, iop/kernel/include/sysclib.h, iop/memorycard/mcman/src/main.c, iop/memorycard/mcman/src/ps2mc_fio.c, iop/network/smbman/src/smb_fio.c, iop/system/iopmgr/src/commandline.c, iop/system/iopmgr/src/imports.lst, iop/usb/camera/src/ps2cam.c
Improvements related to sysclib headers.
Some new warnings found by using GCC builtin functions were also fixed.
=> Improvements related to sysclib headers

common/include/cdvd-ioctl.h, common/include/libcdvd-common.h, iop/kernel/include/cdvdfsv.h, iop/kernel/include/cdvdman.h
Add additional CDVD related definitions.
RPC related definitions will be in a separate PR (since I'm still planning a way to generate the RPC bindings)
=> Additional CDVD related definitions

iop/kernel/include/dmacman.h, iop/kernel/include/excepman.h, iop/kernel/include/heaplib.h, iop/kernel/include/loadcore.h, iop/kernel/include/sifman.h, iop/kernel/include/timrman.h
Add more definitions to IOP module headers.
Implementations will be in separate PRs.
=> Add more definitinos to IOP module headers

iop/debug/ioptrap/src/ioptrap.c, iop/kernel/include/excepman.h, iop/kernel/include/sifman.h
=> More IOP definition fixes

iop/dev9/extflash/Makefile, iop/dev9/extflash/include/fls.h, iop/dev9/extflash/src/extflash.c
=> Expose extflash library

ee/Makefile, ee/mpeg/Makefile, ee/mpeg/include/libmpeg.h, ee/mpeg/src/libmpeg.c, ee/mpeg/src/libmpeg_core_c.c, ee/mpeg/src/libmpeg_internal.h
Libmpeg now builds on new toolchain, but it is unverified.
=> libmpeg related fixes

common/include/hdd-ioctl.h
=> Add dvr_hdd devctls

iop/dev9/extflash/include/fls.h, iop/dev9/extflash/src/extflash.c
Various fixes for external flash rom.
=> External flash rom driver fixes

ee/rpc/cdvd/Makefile, ee/rpc/cdvd/src/scmd.c
=> rpc/cdvd: add sceCdNoticeGameStart

ee/kernel/src/rom0_info.c
Excluded arcade boards (that have TZ in RomName)
=> More precise check for TOOL (DTL-T10000)

iop/fs/bdm/Makefile, iop/fs/bdm/src/part_driver.c, iop/fs/bdmfs_vfat/Makefile, iop/fs/bdmfs_vfat/src/fat_driver.c, iop/fs/bdmfs_vfat/src/fat_write.c, iop/fs/bdmfs_vfat/src/include/common.h, iop/iLink/IEEE1394_bd/Makefile, iop/iLink/IEEE1394_disk/Makefile, iop/iLink/IEEE1394_disk/src/fat_driver.c, iop/iLink/IEEE1394_disk/src/fat_write.c, iop/iLink/IEEE1394_disk/src/include/usbhd_common.h, iop/iLink/IEEE1394_disk/src/part_driver.c, iop/usb/usbd/Makefile, iop/usb/usbd/src/interface.c, iop/usb/usbhdfsd/Makefile, iop/usb/usbhdfsd/src/fat_driver.c, iop/usb/usbhdfsd/src/fat_write.c, iop/usb/usbhdfsd/src/include/usbhd_common.h, iop/usb/usbhdfsd/src/part_driver.c, iop/usb/usbmass_bd/Makefile
Change filesystem macro to use usigned to prevent overflow
=> Fix for external HDD drives larger than 1Tb

iop/network/smbman/src/smb.c
=> smbman: use setStringField to set empty string on string field in FIND_NEXT2 packet

ee/math3d/include/math3d.h, ee/math3d/src/math3d.c
Addition and cross-product are pretty fundamental vector operations that were missing, so I've added them. In addition, being able to calculate some kind of normal for a triangle is important for getting any sort of shaded graphics without hardcoding normals (as is done in the hires example) so it's worth including so generating models algorithmically is made slightly more convenient.
There may well be a way to optimise this using some assembly but idk how to approach that
=> Add functions for calculating normals

.github/workflows/compilation.yml, Makefile, ee/Rules.make, ee/network/tcpip/Makefile, ee/network/tcpip/src/include/arch/cc.h, iop/Rules.make, iop/debug/ioptrap/Makefile, iop/dev9/poweroff/src/poweroff.c, iop/fs/fakehost/src/fakehost.c, iop/fs/filexio/src/fileXio_iop.c, iop/fs/http/src/ps2http.c, iop/iLink/iLinkman/src/iLink_intr.c, iop/memorycard/mcman/src/main.c, iop/memorycard/mcman/src/mcman-internal.h, iop/memorycard/mcman/src/mcsio2.c, iop/memorycard/mcman/src/ps1mc_fio.c, iop/memorycard/mcman/src/ps2mc_fio.c, iop/memorycard/mcserv/src/mcserv.c, iop/memorycard/mcserv/src/mcserv.h, iop/tcpip/tcpip-base/include/arch/cc.h
I added -Wno-error in ee/tcpip module cause external lwip module has some warnings
=> Fix and adjust "debug" version of all utilities

iop/fs/bdm/src/part_driver.c, iop/fs/bdmfs_vfat/src/fat_driver.c
This pr for fixing some issues with USB without MBR scheme.
=> BDM: add support for Removable media

iop/kernel/include/modload.h, iop/kernel/include/romdrv.h
Adds more definitions from modload, and adds definitions for romdrv.
=> More IOP definitions

iop/fs/bdmfs_fatfs/src/fs_driver.c
Solves this issue:
https://github.com/ps2homebrew/Open-PS2-Loader/issues/662
=> Fixed file stat

ee/kernel/Makefile, ee/kernel/src/timer_alarm.c
Follow the same approach for generating a `.o` per function for the `timer_alarm.c` functions
=> Separate functions for timer alarm

common/include/usbhdfsd-common.h, iop/fs/bdmfs_fatfs/src/fs_driver.c, iop/fs/libbdm/include/bd_defrag.h, iop/fs/libbdm/src/bd_defrag.c
The code has been updated to support a variable number of fragments, allowing more than the fixed number of 10 fragments. It's not up to the requesting application to choose what the maximum number of fragments it.
=> BD fragmentation support: variable number of fragments

common/include/dev9regs.h, iop/usb/usbd/include/usbd.h
=> USBD and DEV9 definitions backwards compatibility

ee/kernel/include/syscallnr.h, ee/kernel/src/alarm.c
More symbols and changes to make it more inline with official software.
=> Kernel lib changes

common/Rules.release, common/include/arpa/inet.h, common/include/netdb.h, common/include/netinet/in.h, common/include/sys/socket.h, common/include/tcpip.h, ee/network/tcpip/Makefile, ee/network/tcpip/include/ps2ip.h, ee/network/tcpip/src/ps2ip_shims.c
Changes mainly for porting cURL.
=> More portable network library

iop/fs/libbdm/src/bd_cache.c
I wasn't happy with the performance of the 8 block LRU (Least Recently Used) cache. So I've been looking into different algorighms that would fit our usecase:
**LRU** - Least Recently Used
With LRU the least recently used blocks will be evicted. But the problem with LRU is that many blocks that are only used once can quickly flush out the (32 block) cache.
**LFU** - Least Frequently Used
With LFU the least frequently used blocks will be evicted. This solves the LRU problem, but creates the problem of cache pollution. Where for instance 31 blocks of the 32 block cache have high usage counts, and so only 1 block can be used for all new accesses. Highly used blocks in the past will stay present in the cache forever.
**LFUDA** - Least Frequently Used with Dynamic Aging
To overcome the issue …
=> libbdm: improve caching by a LOT

iop/fs/bdmfs_fatfs/src/fs_driver.c
=> bdmfs_fatfs: statically allocate memory for FIL and DIR structures

iop/network/smap/Makefile, iop/network/smap/src/imports.lst, iop/network/smap/src/include/ipstack.h, iop/network/smap/src/include/main.h, iop/network/smap/src/include/xfer.h, iop/network/smap/src/smap.c, iop/network/smap/src/xfer.c
Some changes to make switching out the IP stack easier.  
Added receive polling when there are a large amount of packets.
=> SMAP related cleanup

iop/sio/mx4sio_bd/src/mx4sio.c
spisd_write_multi_block seems broken?
=> mx4sio: fix writing, works but is still terribly slow

common/include/libcdvd-common.h, ee/rpc/cdvd/include/libcdvd.h, ee/rpc/cdvd/src/ncmd.c, ee/rpc/cdvd/src/scmd.c, iop/kernel/include/cdvdman.h
Corrections to make it more in line with CDVDMAN/CDVDFSV code.
=> libcdvd: apply command definition corrections

iop/usb/usbmass_bd/src/imports.lst, iop/usb/usbmass_bd/src/usb_mass.c
Fixes issues related to incorrect initialization when multiple devices are connected at module load.
=> usbmass_bd multiple device fixes

iop/dev9/poweroff/Makefile
=> Disable IOP GCC 12 errors 

iop/fs/bdmfs_fatfs/src/fs_driver.c
I never actually tested outside of the root directory.
This will fix the issue of file finding not working
=> Fixes for bdmfs_fatfs

Defs.make, iop/Rules.make, iop/kernel/include/irx.h, samples/Makefile.iopglobal_sample, samples/Makefile.pref_sample
Depends on https://github.com/ps2dev/ps2toolchain-iop/pull/16
=> Revert to old IRX toolchain

ee/debug/include/debug.h, ee/debug/src/scr_printf.c
I haven't tested it, only saw that putchar actually spits colored chars so i wanted to try
=> font and cursor customizable colors for scr_printf

.github/workflows/gh-pages.yml, Doxyfile
[Current aspect of PS2SDK docs](https://ps2dev.github.io/ps2sdk/)
versus
[How it will look like after merging](https://israpps.github.io/ps2sdk/)
=> Better CSS for documentation 

ee/Rules.bin.make, ee/Rules.make, ee/elf-loader-nocolour/Makefile, ee/elf-loader-nocolour/src/loader/Makefile, ee/elf-loader/Makefile, ee/elf-loader/src/.gitignore, ee/elf-loader/src/loader/Makefile, ee/elf-loader/src/loader/src/loader.c
=> ELF loader no debug

ee/elf-loader/src/loader/src/loader.c
The red color was duplicated, now we have a separate color per step
=> Improve colors in the ELF loader

iop/kernel/include/modload.h, iop/security/secrman/src/secrman.c
More useful symbol names and types.
=> Implement types to modload and secrman from loadfile

iop/system/stdio/Makefile, iop/system/stdio/README.md, iop/system/stdio/src/exports.tab, iop/system/stdio/src/imports.lst, iop/system/stdio/src/irx_imports.h, iop/system/stdio/src/stdio.c
=> Add STDIO module

common/external_deps/Makefile, dowload_dependencies.sh
Attempt to fix multi job build
=> Clone lwip to temporary directory, then rename after cloning

common/include/sys/random.h, ee/libcglue/Makefile, ee/libcglue/src/glue.c
Add getrandom implementation.
Mainly intended for the wolfssl port
=> Add getrandom implementation

ee/rpc/remote/include/librm.h, ee/rpc/remote/remote.md
Fix #392, Fix #393
|Before|After|
| -- | -- |
|<img src="https://user-images.githubusercontent.com/2995486/212488586-03b45f05-2ba5-443f-a562-2f389b5552a5.png">|<img src="https://user-images.githubusercontent.com/2995486/212488589-17118cb0-d47a-43a3-a2f9-4065fa8b6a38.png">|
=> librm fixes

tools/adpenc/src/adpcm.c, tools/adpenc/src/main.c
Since conversion from 8bit wave to 16bit is pretty trivial this saves us the need to use an additional tool for the conversion
=> Add support for 8bit wave files in adpenc

ee/rpc/audsrv/src/audsrv_rpc.c
Finally figured out how to test things, also have a game port mostly working now with this helps as well :D
=> audsrv: Fix sterio calculations

iop/sound/ps2snd/src/adpcm-stream.c
My sounds where streaming at the wrong speed since they had a pitch different from `0x1000`.
This also avoid the need for the caller to set the correct channel number as that can also be read from the file header.
=> Read pitch and channels from header instead of hardcoding them

iop/fs/bdmfs_fatfs/src/fs_driver.c, iop/fs/bdmfs_vfat/src/fs_driver.c, iop/iLink/IEEE1394_disk/src/fs_driver.c, iop/usb/usbhdfsd/src/fs_driver.c
Follow-up to https://github.com/ps2dev/ps2sdk/pull/396 which did this in iomanX
=> Bump MAX_FILES to 128 in fs drivers

ee/debug/include/debug.h, ee/debug/src/scr_printf.c
Expose clear line
Implement clear char
=> Improve screen debug clear functions

ee/libcglue/Makefile, ee/libcglue/src/glue.c
This PR has been created thanks to @AKuHAK for investigating an issue after merging #429 
Create a specific method for transform errno returning 64 bits
=> Fix issue with lseek64

ee/libcglue/src/lock.c, ee/mpeg/src/libmpeg_core_c.c
=> Fix compilation after newlib merge

ee/sbv/src/slib.c
=> Fix compilation of slib

iop/network/udptty/src/udptty.c
- also hook stderr FDs
- Dont close all FDs then open all of them. Close and Open right away each of them
=> [UDPTTY]: hook stderr too and close FDs in order

ee/kernel/src/sifrpc.c
by krat0s
This will solve some freezes in some applications after multiple IOP resets
=> krat0s: fix RPC calls to properly free packets as per original code

common/include/gs_gp.h
For #460, this updates the bitmask for the addresses in MIPTBP
=> Fix MIPTBP addresses bitmask

iop/hdd/apa-bdm/Makefile, iop/hdd/apa-iomanx/Makefile, iop/hdd/apa/Makefile, iop/hdd/apa/src/hdd.c, iop/hdd/apa/src/hdd_blkio.c, iop/hdd/apa/src/hdd_blkio.h, iop/hdd/apa/src/hdd_fio.c, iop/hdd/apa/src/hdd_fio.h, iop/hdd/apa/src/imports.lst, iop/hdd/apa/src/irx_imports.h, iop/hdd/hdck/src/hdd_blkio.h, iop/hdd/hdsk/src/hdd_blkio.h, iop/hdd/libapa/src/apa.c, iop/hdd/libapa/src/free.c, iop/hdd/libapa/src/journal.c, iop/hdd/libapa/src/password.c
Adds support for BDM and iomanX backing store for apa driver.
=> feature: Add support for BDM and iomanX backing store for apa driver

ee/kernel/Makefile, ee/kernel/include/kernel_util.h, ee/kernel/src/kernel_util.c, ee/libpthreadglue/src/include/ps2_osal.h, ee/libpthreadglue/src/osal.c, ee/network/tcpip/include/ps2ip.h, ee/network/tcpip/src/ps2ip.c, ee/network/tcpip/src/sys_arch.c
Seems like multiple places are using this pattern, so refactor it into a separate function
=> Refactor WaitSema with a timeout into a separate function

ee/kernel/Makefile, ee/kernel/include/delaythread.h, ee/kernel/include/kernel.h, ee/kernel/include/timer.h, ee/kernel/include/timer_alarm.h, ee/kernel/samples/timer_alarm/test_alarm.c, ee/kernel/samples/timer_alarm_stop/test_alarm_stop.c, ee/kernel/src/delaythread.c, ee/kernel/src/initsys.c, ee/kernel/src/kernel_util.c, ee/kernel/src/timer.c, ee/kernel/src/timer_alarm.c, ee/libpthreadglue/src/osal.c
=> Rework EE timer to more closely match official behavior

iop/fs/filexio/src/fileXio_iop.c
eg: if an open request is perfomed, path and open mode is informed
=> filexio: inform of important RPC payload data on debug builds

ee/libcglue/Makefile, ee/libcglue/include/ps2sdkapi.h, ee/libcglue/src/cwd.c, ee/libcglue/src/glue.c, ee/rpc/filexio/Makefile, ee/rpc/filexio/src/fileXio_ps2sdk.c
`_ps2sdk_ioctl2` has been exposed
cwd length validation has been improved
=> Fdmap improvements 240118

iop/system/Makefile, iop/system/timrman/src/timrman.c, iop/system/timrmanp/Makefile
For completeness/documentation purposes
=> Add 'p' variant of timrman

iop/kernel/include/loadcore.h, iop/kernel/include/sifcmd.h, iop/kernel/include/sifman.h, iop/kernel/include/sysmem.h, iop/kernel/include/xloadcore.h, iop/kernel/include/xmodload.h, iop/kernel/include/xsysmem.h
More correct symbols and types
=> Module definition improvements 240123

ee/libcglue/src/ps2sdkapi.c, ee/rpc/filexio/src/fileXio_ps2sdk.c
=> Check if _fstat is existent for stat operation

ee/kernel/src/timer.c
=> fix: timer, make next compare event comparison signed

samples/Makefile.eeglobal_sample, tools/romimg/Makefile, tools/romimg/src/ELF.h, tools/romimg/src/SonyRX.c, tools/romimg/src/SonyRX.h, tools/romimg/src/dprintf.h, tools/romimg/src/main.c, tools/romimg/src/platform.c, tools/romimg/src/platform.h, tools/romimg/src/romimg.c, tools/romimg/src/romimg.h
saves time if developer has to deal with ioprp images.
Only thing left is to include `libiopreboot`.
=> add romimg to tools & recipe for IOPRP Images

tools/bin2c/src/bin2c.c
Fixes compilation on newer glibc
=> Add mode argument to output file of bin2c

iop/debug/ppctty/README.md, iop/debug/ppctty/src/main.c
untested yet
Dont forget to squash and merge when merging
=> [ppctty] simpler DECKARD console check

ee/libcglue/Makefile, ee/libcglue/src/glue.c
This PR requires https://github.com/ps2dev/newlib/pull/11 to be merged before.
Cheers.
=> Adding `_execve`

ee/libcglue/src/cwd.c
Drive path parsing is now done in a similar way as ioman(X) does it  
`hdd` added to path exclusions
=> Improvements to drive cwd handling of libcglue

ee/libcglue/src/cwd.c
=> Revert "Improvements to drive cwd handling of libcglue"

iop/dev9/pvrdrv/src/dvrdrv.c, iop/dvrp/dvr/src/dvr.c, iop/dvrp/dvrav/src/dvrav.c, iop/dvrp/dvrdv/src/dvrdv.c, iop/dvrp/dvrfile/src/dvrfile.c, iop/dvrp/dvripl/src/dvripl.c, iop/dvrp/dvrmisc/src/dvrmisc.c, iop/hdd/apa/src/hdd.c, iop/hdd/libapa/include/libapa.h, iop/hdd/libapa/src/cache.c, iop/hdd/libpfs/include/libpfs.h, iop/hdd/libpfs/src/cache.c, iop/hdd/pfs/src/pfs.c, iop/memorycard/mcman/src/imports.lst, iop/memorycard/mcman/src/main.c, iop/memorycard/mcman/src/mcdev.c, iop/memorycard/mcman/src/mcman-internal.h, iop/memorycard/mcman/src/mcsio2.c, iop/memorycard/mcserv/src/imports.lst, iop/memorycard/mcserv/src/mcserv.c
Backwards compatible module unload support for pvrdrv, dvr, dvrav, dvrdv, dvrfile, dvripl, dvrmisc, apa, pfs, mcman, mcserv
=> Module unload support

tools/bin2c/src/bin2c.c
=> Putting back previous bin2c

tools/bin2c/src/bin2c.c
This should fix compiling with -Wall and -Werror
=> Fix unused variable warning

iop/usb/usbmass_bd/src/scsi.c
=> Misalignment workaround for usbmass_bd

ee/rpc/audsrv/samples/playadpcm/playadpcm.c, ee/rpc/filexio/samples/main.c, ee/rpc/multitap/samples/mtap_sample.c, ee/rpc/padx/samples/padx.c
Didn't think to test these before.
=> Fix building samples on gcc14

iop/kernel/include/secrman.h, iop/security/secrman/src/exports.tab, iop/security/secrman/src/secrman.c, iop/security/secrman_arcade/Makefile
this time a clean implementation
=> implement arcade SECRMAN

ee/libcglue/include/ps2sdkapi.h
=> [libcglue] add macro for system 2x6 conflictive code override

ee/debug/src/scr_printf.c
=> [src_printf]: implement `\r`

samples/ps2dev.cmake, samples/ps2dev_iop.cmake
=> Revert "build: assigned include dirs and lib dirs the correct way"

samples/Makefile.iopglobal_sample
This reverts commit e04f945323663b15e4c575c09754fedf5a00566f, reversing changes made to 234a378e530a5c2fa0d137805ec5ab56b84a1170.
=> [NFC] Revert "Merge pull request #639 from Wolf3s/gcc-acient"

iop/debug/ppctty/src/tty.c
=> [ppctty]: set appropiate flags for tty device

ee/kernel/include/timer_alarm.h
This commit adds C++ support to Timer Alarms.
=> Update timer_alarm.h for C++ support

iop/system/iomanx/src/imports.lst, iop/system/iomanx/src/iomanX.c, iop/system/iomanx/src/irx_imports.h
This mainly adds the dummy TTY, unused errno, unknown device message, and device linked list.
Tested wLE can launch itself and pfsshell can list files.
=> iomanX feature update

iop/system/iomanx/src/iomanX.c
=> iomanX null terminate after strncpy in parsefile

common/include/dev5_mmio_hwport.h, iop/network/spduart/src/spduart.c
Add descriptions for dev5 and uart registers
=> Improve register descriptions 20250111

ee/erl/src/erl.c
On assembly level, the PS2 need to allocate addresses divided in two 16bit immediate loads into upper and lower 32bits of a register in order to get a pointer to the memory address. The issue happens when you are combining addresses which lower bits are greater than 0x8000, ERL library linker is supposed to add 1 to the upper 16 bit of the address. 
(E.g.: 0x20, 0x8001 -> 0x218001) Well, of course it doesn't do it, which leads to a lot of invalid pointers in bigger ERL binaries, This PR fixes it (in a dirty way), predicting the lower address and then adding a bit significance compensation, in order to relocate to the right address. That fix was widely tested on my plugin system, which injects compiled C code in GTA San Andreas.
=> fix: recalculate addresses when lower bits are greater than 0x8000

ee/erl/src/erl.c
This PR adds some level of support for addend on relocations. Since RELA type was added recently, I didn't implement any support for it. It should cover most of the cases, tested while developing AthenaEnv ERL support.
=> feat: add addend to target relocation address

iop/sound/libsd/src/libsd.c
=> [libsd] Use getter/setter for MMIO access

.github/workflows/compilation.yml
=> Upload irxs to workflows

iop/system/sio2man/src/sio2man.c
Fix issue introduced in #746 commit https://github.com/ps2dev/ps2sdk/commit/fe8fcb1d48a30da99f8f4603d1bff175cc8b3c81.
Replaces #771 ?
Fixes https://github.com/ps2homebrew/Open-PS2-Loader/issues/1529
=> Fix sio2man issue (black screen on OPL)
