iop/kernel/include/thpool.h
As it is right now, `thpool.h` is unusable due to a missing parenthesis. This PR fixes that issue.
=> IOP thpool header fix

.travis.yml
This will test every push to master as well as all pull requests and report whether PS2SDK compiles and installs cleanly or not.
Utilizes https://github.com/mlafeldt/docker-ps2dev for cross-compiling.
=> Continuously test PS2SDK using Travis CI

iop/kernel/include/thbase.h
Add declarations for CancelWakeupThread and iCancelWakeupThread functions that were missing from `thbase.h`.
=> Add declarations for CancelWakeupThread functions.

ee/draw/samples/cube/Makefile.sample, ee/draw/samples/teapot/Makefile.sample, ee/draw/samples/texture/Makefile.sample, ee/font/samples/Makefile.sample, ee/graph/samples/Makefile.sample, ee/kernel/src/osdsrc/Makefile, ee/kernel/src/tlbsrc/Makefile, ee/libgs/samples/libgs_doublebuffer/Makefile.sample, ee/libgs/samples/libgs_draw/Makefile.sample, ee/mpeg/samples/Makefile.sample, iop/iLink/IEEE1394_disk/Makefile, iop/iLink/IEEE1394_disk/src/fat_driver.c, iop/iLink/IEEE1394_disk/src/fat_write.c, iop/network/netman/Makefile, iop/network/smap/Makefile, iop/tcpip/tcpip/Makefile, iop/usb/mouse/Makefile, samples/Makefile.iopglobal_sample
fixed debug build of i.Link driver
fixed sample makefiles
added imports and exports into common iop makefiles
for better use in external projects
Now it is possible to get rid of iop PS2SDK-style
Rules.make and use instead Makefile.iopglobal
-include Rules.make
+include $(PS2SDK)/samples/Makefile.pref
+include $(PS2SDK)/samples/Makefile.iopglobal
=> added imports and exports into common iop makefiles

ee/Rules.make, samples/Makefile.eeglobal_cpp_sample, samples/Makefile.eeglobal_sample
To keep things going here is a pull request to fix C++ support when using the samples makefiles, and when using newer compilers.
I have tested C++ support when using gcc 3.2.3 and Makefile.eeglobal_cpp. The rest is not tested but looks good to me.
=> C++ support fix

ee/kernel-nopatch/Makefile, ee/kernel/Makefile, ee/kernel/include/kernel.h, ee/kernel/src/glue.c, ee/kernel/src/initsys.c, ee/kernel/src/kernel.S, ee/kernel/src/srcfile/src/alarm.c, ee/libc/Makefile, ee/libc/src/stdio.c, ee/libc/src/stdlib.c
Modified libkernel to allow building with no support for patches (for ease of maintaining/building loader-like/resident projects). Such projects can be built without the patches by linking to libkernel-nopatch instead of libkernel.
Also added a (missing) workaround for the old SetAlarm and ReleaseAlarm, when the alarm patch is not built.
I also moved around internal data of libc, to reduce the bloat that is linked to by crt0 itself. However, these changes do not totally eliminate the bloat of libc (the use of a custom crt0 is required).
On a side note, if a host program is compiled with the alarm patch and it loads an ELF loader, the ELF loader should reside at 0x00084000 instead of 0x00082000. Otherwise, it may overwrite the alarm patch, which may cause an exception. This is done by the …
=> Libkernel compatability patch for loader-like/resident projects

iop/dev9/atad/Makefile, iop/dev9/atad/src/ps2atad.c, iop/dev9/dev9/Makefile, iop/dev9/dev9/src/ps2dev9.c
This pull request contains workarounds in DEV9 & ATAD for bad GameStar adaptors.
As it appears that the current method of detecting a GameStar is not so effective, please **do not** merge this pull request yet.
=> Workarounds in DEV9 & ATAD for bad GameStar adaptors

ee/Rules.make, ee/erl-loader/Makefile, ee/kernel/src/eenull/Makefile, ee/kernel/src/osdsrc/Makefile, ee/kernel/src/srcfile/Makefile, ee/kernel/src/tlbsrc/Makefile
The recent change to the toolchain adds standard libraries to gcc. Some of these libraries (libc, libkernel) are built by ps2sdk. So ps2sdk needs to use the flag '-nostdlib' when linking or it will fail when compiling for the first time.
I didn't notice this before becouse I normally don't delete the entire $PS2DEV folder before building the toolchain. I still have to do some testing, so don't merge this pr just yet. Sorry for the inconvenience.
=> Use -nostdlib when building ps2sdk

common/include/netman.h, common/include/netman_rpc.h, ee/network/netman/src/include/rpc_server.h, ee/network/netman/src/netman.c, ee/network/netman/src/rpc_server.c, ee/network/tcpip/src/include/lwipopts.h, ee/network/tcpip/src/ps2ip.c, iop/network/netman/src/rpc_client.c, iop/tcpip/tcpip-netman/src/ps2ip.c
This allows receiving from the EE to no require an additional memcpy() statement.
Seems to be working fine now, but I did not notice any improvement in performance (tested with TCP), scoring roughly 69Mbps.
This system was designed based on the idea from [this article](https://community.nxp.com/docs/DOC-330815).
Compared to the current design, this:
- NETMAN's ring buffers have been reduced to 32, down from 64.
- Will always result in at least 32 PBUFs being actively allocated, due to NETMAN's ring buffer size.
- Had LWIP (EE) adjusted to come with 64 PBUFs (up from 60).
- Has a lower EE-side Rx thread priority, so that the while loop around the allocation function (which calls pbuf_alloc) will not prevent the LWIP TCPIP thread (if enabled) from running.
With 32 buffers always allocated, …
=> (NETMAN) Changed NETMAN to support zero-copy receiving for the EE-side protocol stack.

common/include/usbhdfsd-common.h, iop/usb/usbhdfsd/src/fat_driver.c, iop/usb/usbhdfsd/src/fat_write.c, iop/usb/usbhdfsd/src/include/mass_stor.h, iop/usb/usbhdfsd/src/include/scache.h, iop/usb/usbhdfsd/src/scache.c, iop/usb/usbhdfsd/src/usb_driver.c
Modified the FAT driver to allow for long reads and writes.
To make this work with its cache, I made the FAT driver do a cache writeback and invalidation before directly accessing the device.
The cache will hence be only used for caching accesses to the FAT itself.
The cluster size will now hence matter for performance, since the larger the clusters, the longer the possible continuous reads.
The code within usb_driver.c that does the actual sector I/O has also been changed to continue the I/O operation from the USB callback, instead of getting the main thread to do it - which adds overhead. @rickgaiser commented that doing this instead does improve performance.
Finally, I moved the code from configureNextDevice into mass_store_mount and the connect function itself.
I remember somebody …
=> USBHDFSD - I/O Performance Enhancement

common/include/netman_rpc.h, ee/network/netman/src/rpc_client.c, ee/network/netman/src/rpc_server.c, iop/network/netman/src/imports.lst, iop/network/netman/src/rpc_client.c, iop/network/netman/src/rpc_server.c
IOP->EE: use SBUS cause 15 for sharing the Rx thread's status.
EE->IOP: Transfer up to 8 frames without the interrupt.
EE -> IOP communication still uses SIFCMD because the IOP kernel does not allow interrupt handlers to share one cause.
=> (NETMAN) Modified to reduce the use of SIFCMD/interrupts, when possible.

iop/hdd/libpfs/include/libpfs.h, iop/hdd/libpfs/src/bitmap.c, iop/hdd/pfs/src/pfs.h, iop/hdd/pfs/src/pfs_fio.c, iop/hdd/pfs/src/pfs_fioctl.c
The logic behind the Bitmap-management functions was always slightly different in ours, compared to the original.
Recent logs from HDDChecker have shown that PFS may be unable to correctly update the volume bitmap. Perhaps it is due to the homebrew module dividing the index by 32 (instead of 8), before it is left-shifted by 2. As a result, 2 bits of the index will be lost.
Readlink had a faulty check around whether the inode is a symbolic link or not. However, this function still cannot be correctly used from the EE, since fileXio's RPC server does not correctly support readlink().
The IOCTL2 commands for attributes had faulty logic around the main loop corrected.
=> PFS - Fixed faulty logic behind bitmap-management, readlink and attribute IOCTL2 calls

iop/usb/usbhdfsd/src/fat_write.c, iop/usb/usbhdfsd/src/include/scache.h, iop/usb/usbhdfsd/src/scache.c
Changed fat_write.c to use scache_readSector instead of scache_allocSector(), and disabled scache_allocSector. Avoid corrupting the adjacent cluster if:
* Directory entries are added (renaming will destroy and add a new entry).
* The cache block size does not match the cluster size.
* The cache blocks are not aligned to the start of the clusters.
=> (USBHDFSD) Avoid corrupting adjacent clusters, due to a scache design issue.

ee/rpc/multitap/README
This Page Did Not Have Any Mention about The use of Memory Cards With The MultiTap.
Updated The information Regarding the XModule Requirement and Provided Some information on Software Replacement Modules.
Fixed the Incorrect Slot Number Listing For The D Port in the Diagram of the console ports.
Supplemented This Information With The Full Listing of MultiTap Ports, 
Provided the Full port and slot listing By its Letter
Replaced The Multitap detection Example Code With Code From The Mass Format Utility Project
https://github.com/Based-Skid/PS2-Memory-Card-Formatter/blob/master/main.c#L743
=> Updated Multitap Page.

ee/libc/src/ps2sdkapi.c
This PR is just for including the missing `access` function in the `ps2sdkapi.c`
Additional info:
https://linux.die.net/man/2/access
Thanks
=> Include the access function in the ps2sdkapi

samples/Makefile_sample
Some samples were removed due to upgrade, some samples are not optimized for updated newlib, some samples require libc.erl which is missing
=> Updated main Makefile for samples

iop/system/iomanx/src/ioman_sbv.c
This PR just change the default mode creating a folder from `0644` to `0755`
=> Changing default mode_t value for mkdir

ee/draw/src/draw3d.c
Using floats to then cast them back to integer (round towards zero) was overkill. Let's just use integers.
Also removes unused global static variables.
=> draw3d.c: Avoid floats in draw_prim_end()

iop/iLink/IEEE1394_bd/src/imports.lst, iop/iLink/IEEE1394_bd/src/include/module_debug.h, iop/iLink/IEEE1394_bd/src/sbp2_driver.c, iop/iLink/IEEE1394_bd_mini/Makefile, iop/iLink/Makefile, iop/usb/usbmass_bd/src/imports.lst, iop/usb/usbmass_bd/src/include/module_debug.h, iop/usb/usbmass_bd_mini/Makefile
I've had these improvements laying around for some time now:
- Add MINI_DRIVER: add's a 2nd build option for the block devices. This removes all debugging and makes them small enough to be used as OPL in-game drivers.
- IEEE1394: small improvements to compatibility, but compatibility is still poor.
=> Update for BDM drivers

.github/workflows/compilation.yml, README.md, ee/draw/samples/cube/Makefile.sample, ee/draw/samples/teapot/Makefile.sample, ee/draw/samples/texture/Makefile.sample, ee/font/samples/Makefile.sample, ee/graph/samples/Makefile.sample, ee/mpeg/samples/Makefile.sample
Removed -lmf
Added ps2sdk sample compilation stage
ps2sdk samples now available as artifacts
`github.repository_owner` replaced to `ps2dev` cause this environment doesn't work in forked projects, but this Testing Workflow can be useful for forks as well
=> Artifacts and fixes to action

Makefile, ee/Makefile, samples/Makefile_sample
I also had to run dos2unix on build-exports.sh but no matter what I did git always ignored the line endings.
Note that `make install` must still be run without jobs. Some of the prerequisite rules clean up without running `make clean` and I couldn't figure out the correct order to run them to make it work with a job server.
=> Fixed job server

ee/Makefile, ee/elf-loader/Makefile, ee/elf-loader/include/elf-loader.h, ee/elf-loader/src/.gitignore, ee/elf-loader/src/elf.c, ee/elf-loader/src/elf.h, ee/elf-loader/src/loader/Makefile, ee/elf-loader/src/loader/Rules.make, ee/elf-loader/src/loader/loader.c
This PR is for making it easier to load ELFs from other `ELFs`. 
The main concept is inspired by the logic that `uLE` is following for launching `ELFs`, but obviously is improved.
Now, whatever ELF app could load another ELF.
The only steps that need to do is:
Add in the make file the `-lelf-loader` to the linked libraries.
Call `sbv_patch_disable_prefix_check()`
Call `LoadELFFromFile(newELFPath, argc, argv)`
I did test through a dummy test app and in `RetroArch` as well.
Thanks.
=> Create a library to make easier the Loading of ELF files

ee/libc/include/ps2sdkapi.h, ee/libc/src/ps2sdkapi.c, ee/libc/src/sleep.c, ee/libc/src/time.c
Since the newlib port the ps2_clock function uses the clock_t datatype as defined in newlib. Currently newlib has it defined as 64bit, but in different versions this can also be defined as 32bit, causing ps2_clock to then fail.
This PR creates a new ps2_clock_t type that is always 64bit.
=> ps2_clock() needs an u64 datatype

iop/cdvd/cdfs/src/cdfs_iop.c, iop/cdvd/cdfs/src/cdfs_iop.h, iop/cdvd/cdfs/src/imports.lst
Fixes support for DVD video discs.
=> CDFS: DVD video support

ee/libc/src/ps2sdkapi.c
According to the https://linux.die.net/man/2/times:
The tms_cstime field contains the sum of the tms_stime and tms_cstime
values for all waited-for terminated children.
=> Fix problem with clock() function

ee/libc/src/timezone.c
Before this change, the string in _ps2sdk_tzname could be named "GMT+-x" for negative timezone offsets
=> Fix printf specifier for _tzname

ee/libc/src/timezone.c
Changes to make `_ps2sdk_tzname` similar to the POSIX standard
=> Timezone fixes

ee/libc/include/ps2sdkapi.h, ee/libc/src/ps2sdkapi.c, ee/rpc/filexio/src/fileXio_rpc.c
This PR adds lseek64 support to ps2sdk.
Since I'm having issues with my OPL SMB support I have not been able to test but the changes are fairly simple.
=> Add lseek64 function

tools/adpenc/src/main.c
This prevents the warning about the truncation of "APCM" with the usage of strncpy. I don't remember what the actual warning was off hand but I think that is what it was.
=> Use designated initializer for AdpcmHeader

.github/workflows/docker.yml
Hi.
I see that Docker-CI job is failing.
This PR is about:
https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
Proof: 
Thanks!
=> Fix GitHub workflow: Docker-CI

Doxyfile
Hi.
I'm preparing to add packet2 documentation to Doxygen.
I think that it will be required to enable static members in doxygen config file.
Packet2 have a lot of static inline functions which will be not included in doxygen, without changing this option.
Thanks!
=> Doxygen: enable static members

ee/packet2/include/packet2.h, ee/packet2/include/packet2_chain.h, ee/packet2/include/packet2_types.h, ee/packet2/include/packet2_utils.h, ee/packet2/include/packet2_vif.h
Hi.
Added some markups for doxygen, so now, libpacket2 documentation will be visible in github pages :)
Thanks
=> Doxygen: Add markups for libpacket2

ee/draw/samples/Makefile, ee/draw/samples/vu1/main.c, ee/packet2/include/packet2.h, ee/packet2/include/packet2_chain.h, ee/packet2/include/packet2_types.h, ee/packet2/include/packet2_utils.h, ee/packet2/include/packet2_vif.h, ee/packet2/src/packet2.c, ee/packet2/src/packet2_vif.c
Hi.
This is the continuation of PR #155 
@rickgaiser 
+ improvements on libpacket2
+ fixes for GCC11 compatibility
@h4570
+ libpacket2: removed `vif_added_bytes`
+ libpacket2: refactored `packet2_*_close_unpack_*`
Tested on hardware & PCSX2
Thanks!
=> Packet2: GCC11 improvements, refactor of close_unpack()

common/include/as_reg_compat.h, ee/debug/src/hwbp.S, ee/eedebug/src/ee_dbg_low.S, ee/eedebug/src/ee_exceptions.S, ee/mpeg/src/libmpeg_core.s, ee/rpc/cdvd/src/libcdvd.c, ee/rpc/cdvd/src/ncmd.c, ee/rpc/cdvd/src/scmd.c, ee/rpc/multitap/src/libmtap.c, ee/rpc/ps2snd/src/ps2snd.c, ee/rpc/tcpips/src/ps2ipc.c
It can be difficult to find out the register names used by ABI EABI64 and N32. The file as_reg_compat.h should now show crearly the differences, and can also be used to force a .S file to use a specific ABI.
Also all SifBindRpc loops have been made equal, working for both the old and new toolchain. The delay loop with sinple integer counters where optimized by gcc10.
=> Improve as_reg_compat.h and gcc10 compatibility

.github/workflows/compilation.yml, Defs.make, Dockerfile, common/sbus/src/sif2cmd.c, common/tcpip/lwip-2.0.0/src/core/pbuf.c, ee/Makefile, ee/debug/src/callstack.c, ee/kernel/Makefile, ee/kernel/include/kernel.h, ee/kernel/include/sio.h, ee/kernel/src/kernel.S, ee/kernel/src/osdsrc/Makefile, ee/kernel/src/sio.c, ee/kernel/src/srcfile/Makefile, ee/kernel/src/srcfile/src/dispatch.s, ee/libc/include/ps2sdkapi.h, ee/libc/src/ps2sdkapi.c, ee/libc/src/timezone.c, ee/network/tcpip/src/include/arch/cc.h, ee/rpc/filexio/src/fileXio_rpc.c, ee/rpc/hdd/src/libhdd.c, ee/startup/Makefile, ee/startup/src/linkfile, samples/Makefile.eeglobal_cpp_sample, samples/Makefile.eeglobal_sample, samples/Makefile.pref_sample
This PR will update ps2sdk to be compatible with the new GCC10 toolchain for the EE. The current CI (using old toolchain) will fail, becouse not all of these changes are compatible with the old toolchain.
Mostly these are just compatibility fixes, but there are a few things that have been disabled:
- erl-loader: This has never been used as far as I know, and it's been broken for a long time
- mpeg: no-one will probably notice, but I think this should someday be made working with the new toolchain. I will create a github issue about this.
- sio_printf: a function that has been broken since the newlib port. For this I will also create a github issue.
By now the most important ps2 projects (ps2link, RA, OPL, uLE) are compatible with the gcc10 toolchain, so I think it's time to move towards …
=> GCC10 required updates

iop/debug/iopdebug/src/iop_dbg_low.S, iop/debug/iopdebug/src/iop_exceptions.S
If we don't merge these changes, afer merging this one https://github.com/ps2dev/ps2toolchain-iop/pull/2 the `PS2SDK` compilation will fail. However, it can be merged before the `Binutils` PR.
What this PR is doing is importing a missing file in the files that use intrinsic IOP assembly for a proper register name use.
Thanks
=> Fix assemby compilation

iop/kernel/include/stdint.h
I noticed that we don't have an implementation of the C99 fixed-size integer types. I needed a few of them so I figured I'd add the rest and contribute them all.
=> iop: Add stdint.h

ee/elf-loader/src/loader/Makefile, ee/elf-loader/src/loader/loader.c, samples/Makefile.eeglobal_cpp_sample, samples/Makefile.eeglobal_sample
This PR prepare makefiles allowing developer easily to choose if they want to use the newlib nano, using the variable `NEWLIB_NANO = 1` and/or using `libkernel-nopatch` through the variable `KERNEL_NOPATCH = 1`
Additionally, the `elf-loader` is using `libc_nano.a` reducing drastically the size
Thanks
This PR need to be merged after https://github.com/ps2dev/ps2toolchain-ee/pull/11
=> Prepare makefiles for using newlib nano

.github/workflows/compilation.yml, Dockerfile, README.md, ee/elf-loader/src/loader/Makefile, ee/erl-loader/Makefile, ee/libc/Makefile, ee/libc/samples/stdio_tests.c, ee/libc/src/ps2sdkapi.c, ee/libc/src/sleep.c, ee/rpc/cdvd/Makefile, ee/rpc/cdvd/src/scmd.c
This PR does some improvements:
- Remove some declared functions from `/src/ee/libc` because now they are included inside of `newlib`
- Remove the weak reference to time, because now `libcdvd` is one of the standard libraries.
- Fixes wrong return code in the I/O function, now we're setting the `errno` making the toolchain more POSIX and standard.
- Update readme explaining there the standard libraries used.
- Extend the regression test to check return value when error opening files.
This PR should be merged together with https://github.com/ps2dev/ps2toolchain-ee/pull/13
Once this PR is accepted and before get merged, we need to update GCC and newlib branch references.
=> Remove not needed functions from ps2sdklibc because now they are part of newlib

common/include/hdd-ioctl.h, common/include/smapregs.h, common/include/sys/ioctl.h, common/sbus/src/iop_sif2.c, ee/sbv/include/slib.h, iop/Rules.make, iop/cdvd/cdfs/src/cdfs_iop.c, iop/cdvd/cdfs/src/imports.lst, iop/cdvd/cdfs/src/main.c, iop/dev9/atad/src/ps2atad.c, iop/dev9/hdpro_atad/src/hdproatad.c, iop/fs/http/src/imports.lst, iop/fs/http/src/ps2http.c, iop/kernel/include/defs.h, iop/kernel/include/irx.h, iop/kernel/include/loadcore.h, iop/memorycard/mcman/src/main.c, iop/memorycard/mcman/src/sio2man_imports.h, iop/network/smap/Makefile, iop/network/smap/src/smap.c, iop/network/smbman/src/smb.c, iop/network/smbman/src/smb.h, iop/tcpip/tcpips/src/ps2ips.c, iop/usb/camera/src/ps2cam.c, iop/usb/usbd/Makefile, iop/usb/usbd/src/driver.c, iop/usb/usbd/src/hub.c, iop/usb/usbd/src/interface.c, iop/usb/usbd/src/usbdpriv.h, samples/Makefile.iopglobal_sample
Various fixes for various warnings.  
Also, a method to disable usage of GP-relative accesses (and thus disable the save/restore code) was added. For a smooth transition, this will remain enabled for GCC 3.2.3, while it will be properly disabled in GCC 11.
=> IOP fixes for new GCC version

ee/iopreboot/src/SifIopRebootBuffer.c, ee/iopreboot/src/imgdrv/src/imgdrv.c
New IOP compiler messed with the offsets, so search for the offsets instead of hardcoding the values.
=> iopreboot: search for imgdrv offsets instead of hardcoding values

samples/Makefile.eeglobal_cpp_sample, samples/Makefile.eeglobal_sample
This PR exposes `EE_LINKFILE`, allowing the user to override it in case of needs.
This will allow to remove some custom makefiles created specifically for that reason
=> EE_LINKFILE in Makefiles

iop/memorycard/mcserv/src/mcserv.c, iop/memorycard/mcserv/src/mcserv.h, iop/system/padman/src/freepad.h, iop/system/padman/src/padInit.c, iop/system/padman/src/padMiscFuncs.c, iop/system/padman/src/padPortOpen.c, iop/system/padman/src/rpcserver.c
Add backwards compatibility for older `MCSERV` and `PADMAN` RPC clients.
This allows both `libpad` and `libpadx` to be used on the same `PADMAN` module.
This allows `libmc` in both `MC_TYPE_MC` and `MC_TYPE_XMC` modes to be used on the same `MCSERV` module.
This is mainly for compatibility with older software.
=> Add backwards compatibility for older MCSERV and PADMAN RPC clients 

common/include/libcdvd-common.h, ee/rpc/cdvd/include/libcdvd.h, iop/kernel/include/cdvdman.h
Added `sceCdGetToc2` definition  
Corrected `sceCdOpenConfig` definition (it is the same for EE and IOP)
=> More CDVD definitions

iop/hdd/libapa/src/misc.c, iop/hdd/libpfs/src/misc.c
Improved APA/PFS time handling in POSIX environment. Months are no longer off-by-one and timezone is correct.
=> Improved apa/pfs time handling in POSIX environment

iop/kernel/include/setjmp.h
This PR basically moves `setjmp.h` header from `common` to `IOP` folder, because the `EE` one is used from `newlib`
Additionally this specific changes has been neded to do in `newlib`
https://github.com/ps2dev/newlib/pull/2
Thanks
=> setjmp header file

iop/dev9/atad/src/ps2atad.c, iop/hdd/apa-xosd/Makefile, iop/hdd/apa/src/apa-opt.h, iop/hdd/apa/src/hdd.c, iop/hdd/apa/src/hdd_fio.c, iop/hdd/libapa/src/apa.c, iop/hdd/libpfs/include/libpfs.h, iop/hdd/libpfs/src/cache.c, iop/hdd/libpfs/src/journal.c, iop/hdd/libpfs/src/misc.c, iop/hdd/libpfs/src/super.c, iop/hdd/libpfs/src/superWrite.c, iop/hdd/pfs-xosd/Makefile, iop/hdd/pfs/src/pfs-opt.h, iop/hdd/pfs/src/pfs.c, iop/hdd/pfs/src/pfs_fio.c, iop/hdd/pfs/src/pfs_fioctl.c
Add support for specific HDD layout for DESR.
ATAD has been changed so it always returns the non-48-bit total LBA for (emulated) Sony drives. This will allow the added `bhdd` functionality of the APA driver to work correctly. Functionality for drives without the specific security commands should continue to work normally without `bhdd` functionality.
APA and PFS have added support for the `bhdd` device, which will append the total reported non-48-bit LBA and will block writes to `bhdd` (they should be done through `dvr_hdd` and `dvr_pfs` anyways, which I haven't finished reversing how to initialize those interfaces yet).
This will allow access to `__xdata`, `__xcontents` partitions.
=> Add support for specific HDD layout of DESR

iop/hdd/pfs-xosd/Makefile
This will allow the correct name to use used under case-sensitive filesystems
=> pfs-xosd: Correct case of ps2fs-xosd.irx

ee/rpc/filexio/include/fileXio_rpc.h, ee/rpc/filexio/src/fileXio_rpc.c
As many of us have suffered already, `PCSX2` stops printing `print` messages. So this PR could help to mitigate this issue.
Let me try to explain it:
As you know we are using `newlib`, in our apps. The connection between `newlib` and the `ps2sdk` is mainly done here:
https://github.com/ps2dev/ps2sdk/blob/master/ee/libc/src/ps2sdkapi.c
if you take a look, by default, we are `connecting` to `fio` methods, as for instance we have:
```c
#ifdef F__write
int (*_ps2sdk_write)(int, const void*, int) = fioWrite;
int _write(int fd, const void *buf, size_t nbytes) {
return __transform_errno(_ps2sdk_write(fd, buf, nbytes));
}
#endif
```
We can see here how a `_write` function (coming from `newlib`) is redirected to `_ps2sdk_write` which currently is pointing to `fioWrite`.
Till this moment, …
=> fileXio Init improvements

ee/elf-loader/include/elf-loader.h, ee/elf-loader/src/elf.c, ee/elf-loader/src/loader/loader.c
This PR makes some "improvements" for having a safer scenario when we are going to load another `elf` file.
The PR does:
- Clean `bram` (BIOS RAM) space, before the tiny loader is loaded.
- I have copied some code from `OPL` and `wLE`, now the `IOP` is reset and turned to cleaned state before `ExecPS2` is executed
-  Finally, in order to have a better `cwd` value when launching from `HDD`, I have exposed a new function where you can also specify the partition where the `elf` is.
Additional info:
I have implemented all these changes because I was suffering freezes when launching `RA` from `HDD`. 
How `RA` works, every time a rom is loaded, it `re-load` the whole `elf` (they do this, for avoiding possible memory leaks that belong to the specific core).
So the scenario that was failing, was …
=> Improve elf-loader

iop/dev9/atad/include/atad.h, iop/dev9/atad/src/ps2atad.c
Use 48-bit LBA commands on DVRP only when required.
=> atad: use 48-bit LBA commands on DVRP only when required

common/include/hdd-ioctl.h, iop/dev9/dev9/include/dev9.h, iop/dev9/dev9/src/exports.tab, iop/dev9/dev9/src/ps2dev9.c
Add functionality for controlling bits 1 and 2 of `SPD_R_PIO_DATA`  
Adjust `dev9LEDCtl` so that `SPD_R_PIO_DIR` will be set
=> dev9: add functionality for controlling bits 1 and 2 of SPD_R_PIO_DATA

common/include/hdd-ioctl.h, iop/dev9/dev9/include/dev9.h, iop/dev9/dev9/src/exports.tab, iop/dev9/dev9/src/ps2dev9.c
Reverts ps2dev/ps2sdk#215
Reverting this PR because it causes memory issues in IOP for retail consoles.
@uyjulian will create a new PR soon.
=> Revert "dev9: add functionality for controlling bits 1 and 2 of SPD_R_PIO_DATA"

iop/dvrp/dvrfile/src/dvrfile.c
Various improvements to dvrfile.  
There is a particular bugfix to byteswapping the year in `dread`, so the year can now be shown correctly.  
Unaligned pointers and sizes can now be used in `read`/`write`.
=> dvrfile improvements

iop/sound/libsd/include/spu2regs.h, iop/sound/libsd/src/block.c, iop/sound/libsd/src/effect.c, iop/sound/libsd/src/freesd.c, iop/sound/libsd/src/voice.c
This will make it easier to replace it for another backend e.g. spu2 emulator
=> libsd: use macros for read/write registers

iop/fs/bdm/include/bdm.h, iop/fs/bdm/src/bdm.c, iop/fs/bdm/src/part_driver.c, iop/fs/bdmfs_vfat/src/fat_driver.c, iop/iLink/IEEE1394_bd/src/scsi.c, iop/sio/mx4sio_bd/src/mx4sio.c, iop/usb/usbmass_bd/src/scsi.c
This should fix an issue where FAT32 partitions get mounted as extended MBR partition. Since the matching of partitions to file systems is now more strict, it is possible some partitions (anyone using fat12 or fat16 ?) are no longer detected.
=> bdm: filter for supported partition ids

ee/debug/include/debug.h, ee/debug/src/scr_printf.c
Instead of having a bunch of white blocks everywhere if you `scr_printf` and then `scr_setXY`, you can just disable the cursor entirely
Look at the first commit to see the actual changes.
=> Debug: Allow the white cursor to be toggle-able 

ee/rpc/memorycard/include/libmc.h
Useless, however. 
serves documentation purposes
[skip actions]
=> add MCICON_TYPES enum entry for `0x5` type

iop/kernel/include/thbase.h
Found some imports referenced in some IRXs with symbols but not in ps2sdk headers.
=> thbase: add some missing definitions

iop/fs/bdmfs_fatfs/src/fs_driver.c
The highest 32 bit of the file size in the stat struct was not being set.
=> Fixed file size

common/include/usbhdfsd-common.h, iop/fs/bdmfs_fatfs/src/diskio.c, iop/fs/bdmfs_fatfs/src/ff.c, iop/fs/bdmfs_fatfs/src/fs_driver.c, iop/fs/bdmfs_fatfs/src/include/ff.h, iop/fs/libbdm/Makefile, iop/fs/libbdm/include/bd_defrag.h, iop/fs/libbdm/src/bd_defrag.c, iop/fs/libbdm/src/include/module_debug.h
This PR adds a new ioctl2 command: `USBMASS_IOCTL_GET_FRAGLIST`. This lets you request the number of fragments, and a list of the location and sizes of up to 10 fragments.
With this fragment list, the file system driver is no longer needed to read a file with up to 10 fragments.
To process this fragment list, a new library `libbdm` has been added.
Also in this PR all compile warnings of `bdmfs_fatfs` have been fixed.
=> Add (de)fragmentation support to fat32/exFat

ee/kernel/include/timer.h, ee/kernel/src/timer.c
TIM2 is not used and, in theory, reserved for the kernel (but it never uses it). Since we only use it to measure the time, it's easy to configure it (using kmode enter/exit to get around permissions) and use it without much overhead (reads are allowed), while at the same time protecting it from the users.
This will free timer 0 and 1 to be used by homebrew users, and potentially by the timer library in PR #266
=> Move system clock to TIM2

ee/packet2/include/packet2.h
Small change.
It is frustrating me to look at this warning in every compilation.
=> Fixed small variable typo (packet2)

ee/kernel/include/timer_alarm.h, ee/kernel/samples/systemTime/test_systemTime.c, ee/kernel/samples/timer_alarm/test_alarm.c, ee/kernel/samples/timer_alarm_sleep/test_alarm_sleep.c, ee/kernel/samples/timer_alarm_stop/test_alarm_stop.c, ee/kernel/src/timer_alarm.c, ee/libc/include/ps2sdkapi.h, ee/libc/samples/nanosleep/Makefile, ee/libc/samples/nanosleep/Makefile.sample, ee/libc/samples/nanosleep/main.c, ee/libc/src/ps2sdkapi.c, ee/libc/src/sleep.c, samples/Makefile_sample
Now that we have real timers in the `kernel` and we can do `ThreadWaitClock` let's update our tricky `nanosleep` implementation.
=> Improve the nanosleep functionality

ee/packet2/include/packet2_types.h
Typo fix. There is no `18` VIFCode
=> Packet2: Fixed wrong cmd in flusha

iop/usb/usbd/src/driver.c, iop/usb/usbd/src/hcd.c, iop/usb/usbd/src/usbd.c, iop/usb/usbd_mini/Makefile
For OPL's ingame it is important to use as little RAM as possible to preserve game compatibility. This PR adds the creation of a usbd_mini.irx (from the same sources, no copies), that uses over 40KiB less RAM.
Inspired by the ingame usbd module from @sp193 's ps2esdl.
=> usbd: add MINI_DRIVER version that uses 40+ KB less IOP RAM

ee/debug/include/debug.h, ee/debug/src/scr_printf.c
I have added a VA variant of the scr_printf function for usage from functions that already have va_list initialized.
=> ee/debug: introduced scr_vprintf

ee/debug/include/debug.h
Fixes include of `debug.h` when `stdarg.h` isn't included caused by 222e4a19d604cf7876609d45fca43c359c62e82a
=> Add missing stdarg.h include to debug.h

iop/fs/bdmfs_fatfs/src/fs_driver.c
Two fixes in this PR:
1 - Fix for the USBMASS_IOCTL_CHECK_CHAIN ioctl function. This function is used by OPL's VMC files.
2 - Fix for NULL pointer use of mounted_bd
Note that I haven't been able to test the second fix.
@JoseAaronLopezGarcia can you review the changes?
=> Fatfs fixes

samples/Makefile.pref_sample
Fixes the following issue:  
```
make: p: No such file or directory
```
=> Make Makefile.pref_sample contents the same as Defs.make

iop/fs/Makefile, iop/fs/bdm/Makefile, iop/fs/bdm/src/bdm.c, iop/fs/bdm/src/imports.lst, iop/fs/bdm/src/irx_imports.h, iop/fs/libbdm/Makefile, iop/fs/libbdm/include/bd_cache.h, iop/fs/libbdm/src/bd_cache.c
This PR adds a simple 32KiB sector cache to all BDM devices.
Algorithm:
- All reads smaller than 4K will go through the cache (so 512b, 1K, 2k)
- All reads of 4K and larger will **not** use the cache, they are already fast, and only waste cache space.
- Cache will always read in 4K blocks from device (so always more than the requested 512b, 1K, 2k) becouse it is faster
- Cache reads start at the requested sector (so not aligned to 4K)
- Cache has 8 blocks of 4K = 32K
- LRU algorithm
- Read only cache (writes will invalidate the written sectors)
Possible improvements:
- Dynamic cache size (adding an extra parameter to bd_cache_create)
- Better algorithm
Note for OPL:
- This improves GUI loading speeds for all BDM devices
- This **does not** improve ingame speed
- This cache can potentially …
=> Add simple BDM sector cache

iop/network/smap-ps2ip/Makefile, iop/network/smap/Makefile, iop/network/smap/src/exports.tab, iop/network/smap/src/imports.lst, iop/network/smap/src/include/irx_imports.h, iop/network/smap/src/include/main.h, iop/network/smap/src/main.c, iop/network/smap/src/smap.c, iop/network/smap/src/xfer.c
Merge the `smap` sources from the `ps2eth` repository to reduce code duplication.  
Mainly for backwards compatibility.
=> Merge smap from ps2eth

iop/fs/bdmfs_fatfs/src/fs_driver.c
Timestamps should now have the same conversion semantics as the old vfat driver
=> bdm_fatfs: correctly convert timestamps to iox_stat_t format

ee/kernel/src/osd_config.c, ee/libcglue/src/glue.c, ee/libcglue/src/timezone.c, ee/rpc/cdvd/src/scmd.c
`configGetTimezone` and `configSetTimezone` now handle negative timezone offsets.  
`configIsDaylightSavingEnabled` and `configSetDaylightSavingEnabled` now work properly.  
`_timezone` now has the correct sign, so timezone offsets are applied correctly.
=> Time and timezone related improvements

ee/libcglue/src/glue.c
Implementation taken from pspsdk. This function is required for proper save game handling in DevilutionX (Diablo 1 port)
=> Implement truncate

Defs.make, iop/Rules.make, iop/Rules.release, iop/kernel/include/irx.h, iop/startup/Makefile, iop/startup/src/linkfile, samples/Makefile.iopglobal_sample, samples/Makefile.pref_sample, tools/ps2-irxgen/Makefile, tools/ps2-irxgen/src/elftypes.h, tools/ps2-irxgen/src/irxtypes.h, tools/ps2-irxgen/src/ps2-irxgen.c, tools/ps2-irxgen/src/types.h
=> Changes to use unpatched binutils for linking IRX

iop/Rules.make, iop/startup/src/linkfile
If the IRX_ID in the data section is the only thing in the data section, then it got removed by the garbage collector.
This results in an incomplete IRX header, but since the IRX_ID field is optional, the IRX itself would still work. However in some cases when we try to detect IRX'es by name and or version, this could result in the IRX not being found anymore.
=> do not garbage collect sections (can remove .data section)

common/include/iox_stat.h
I was suffering some issues with `ps2link/ps2client` when listing directories and file stats.
The error was just happening with `fileXio` however with `fio` it worked properly.
After hours of investigation, we faced (with the help of @F0bes) that it was an alignment issue. Something really similar to the error in `wLaunchELF` https://github.com/ps2homebrew/wLaunchELF/pull/89/files
I have tested it in real hardware and in `PCSX2`, in both places, it is working as expected.
Cheers
=> Add alignement to iox_stat_t and iox_dirent_t

common/include/errno.h
FIxing this kind of warnings:
```
error: C++ style comments are incompatible with C90 [-Werror]
```
=> Fix comments error in C90 style

ee/libgs/src/dma.c
libgs shares a block of data for all of it's GIF data.
Because this block was marked as non-volatile and there were no memory barriers in place, the compiler was assuming that data in this block was unused in GsDmaSend(_tag).
This ended up having the GIF tag write be delayed until later, effectively sending 0 as a tag to the GIF (oops!).
This made it so libgs was broken both on hardware and emulation.
This PR adds a memory barrier by clobbering memory.
Thanks goes to TellowKrinkle :)
=> Libgs: Treat EE->GIF data as volatile like (Fixes libgs)

iop/memorycard/mcman/src/main.c, iop/memorycard/mcman/src/mcsio2.c, iop/memorycard/mcman/src/ps1mc_fio.c, iop/memorycard/mcman/src/ps2mc_fio.c
Avoids the situation where a crash may occur when accessing an unformatted memory card
=> mcman: Proper setting and checking of mcdi->cardform

iop/system/padman-old/Makefile, iop/system/padman/Makefile, iop/system/padman/src/imports.lst, iop/system/padman/src/irx_imports.h, iop/system/padman/src/padData.c, iop/system/padman/src/padInit.c, iop/system/padman/src/padMiscFuncs.c, iop/system/padman/src/padPortOpen.c, iop/system/padman/src/rpcserver.c, iop/system/rpadman/Makefile, iop/system/rsio2man/Makefile, iop/system/sio2log/Makefile, iop/system/sio2man-old/Makefile, iop/system/sio2man/Makefile, iop/system/sio2man/src/exports.tab, iop/system/sio2man/src/sio2man.c
Backwards compatibility for old SIO2MAN/PADMAN.  
These are implemented as module variants, instead of attempting to combine the different versions of the RPC interface into one module.  
This mainly serves as a OSS replacement for `rom0:SIO2MAN` and `rom0:PADMAN` which old homebrew may rely on.
=> Add SIO2MAN/PADMAN old API variants

iop/kernel/include/iomanX.h
=> iomanX: Ensure that IOMANX_OLD_NAME_ADDDELDRV also renames import table symbol

iop/Rules.make
`-Werror` was removed by mistake.
Add it back in.
=> iop/Rules.make: readd -Werror

iop/fs/bdm/Makefile
Fixes one instance of interdependency issue when compiling with multiple jobs
=> bdm: Compile libbdm if not already compiled

iop/fs/bdm/Makefile
@uyjulian I have reverted this PR because `ps2sdk-ports` was failing 
https://github.com/ps2dev/ps2sdk-ports/actions/runs/3553932933/jobs/5969726140
```bash
/usr/local/ps2dev/ps2sdk/bin/bin2c /usr/local/ps2dev/ps2sdk/iop/irx/sio2man.irx sio2man_irx.c sio2man_irx
/usr/local/ps2dev/ps2sdk/bin/bin2c /usr/local/ps2dev/ps2sdk/iop/irx/iomanX.irx iomanX_irx.c iomanX_irx
/usr/local/ps2dev/ps2sdk/bin/bin2c /usr/local/ps2dev/ps2sdk/iop/irx/fileXio.irx fileXio_irx.c fileXio_irx
/usr/local/ps2dev/ps2sdk/bin/bin2c /usr/local/ps2dev/ps2sdk/iop/irx/mcman.irx mcman_irx.c mcman_irx
/usr/local/ps2dev/ps2sdk/bin/bin2c /usr/local/ps2dev/ps2sdk/iop/irx/mcserv.irx mcserv_irx.c mcserv_irx
/usr/local/ps2dev/ps2sdk/bin/bin2c /usr/local/ps2dev/ps2sdk/iop/irx/bdm.irx bdm_irx.c bdm_irx
Error opening …
```
=> Revert "bdm: Compile libbdm if not already compiled"

ee/rpc/memorycard/src/libmc.c
=> libmc: Align variables that are accessed as uncached or that have flushed data cache

ee/network/tcpip/Makefile, iop/tcpip/tcpip/Makefile
Mainly to assist other (non-GNU) Make implementations when building with multiple jobs
=> Expand tcpip makefile patterns to have pattern per file instead of root dir

iop/network/smap-modular-netman/Makefile, iop/network/smap-modular-none/Makefile, iop/network/smap-none/Makefile, iop/network/smap/Makefile, iop/network/smap/include/smap_modular.h, iop/network/smap/src/exports.tab, iop/network/smap/src/include/ipstack.h, iop/network/smap/src/include/main.h, iop/network/smap/src/ipstack.c, iop/network/smap/src/main.c, iop/network/smap/src/smap.c, iop/network/smap/src/xfer.c
Mainly intended for lightweight usages, like UDPBD, without needing to add its network stack code into the SMAP module itself.
=> Implement SMAP modular hook interface

iop/system/sysclib/src/eyalroz_printf/printf.c
This allows, when paired with `STDIO` module's `printf` or `fdprintf` function, to output correctly.
=> sysclib: In prnt function, call with flush commands when finished

.github/workflows/compilation.yml, .github/workflows/docker.yml, Dockerfile
This PR is to avoid having circular dependencies between `gsKit` and `ps2sdk-ports`, so now `gsKit` is part of `ps2sdk-ports`
=> Dispatch to `ps2sdk-ports` instead `gsKit`

ee/libcglue/Makefile, ee/libcglue/include/ps2sdkapi.h, ee/libcglue/samples/mem_test/main.c, ee/libcglue/src/glue.c, ee/libcglue/src/init.c, ee/libcglue/src/rtc.c
Mainly for applications that call `time` or related functions very often
=> Changes to use and cache real time clock value based on offset from timer

common/sbus/src/ps2_dbg.c, common/sbus/src/sif2cmd.c, iop/memorycard/mcserv/src/mcserv.c, iop/network/smbman/src/auth.c, iop/network/smbman/src/des.c, iop/sound/audsrv/src/adpcm.c, iop/sound/audsrv/src/audsrv.c, iop/sound/audsrv/src/cdrom.c, iop/usb/camera/src/ps2cam.c, iop/usb/mouse/src/ps2mouse.c
The IRX loader can only handle max alignment of 16 bytes.  
Future updates to the toolchain will make this a hard requirement.
=> Fix alignment of variables in IOP modules to be max 16 bytes

ee/rpc/audsrv/include/audsrv.h, ee/rpc/audsrv/samples/playadpcm/playadpcm.c, ee/rpc/audsrv/src/audsrv_rpc.c, iop/sound/audsrv/include/audsrv.h, iop/sound/audsrv/src/adpcm.c, iop/sound/audsrv/src/rpc_server.c
This adds a 3rd parameter to `audsrv_adpcm_set_volume()` which makes it possible to pan the sound left or right, allowing for positional audio in games.
-100: Sound is all the way to the left
-50: Sound is 45° to the left (50% volume on the right)
0: Sound is centered
50 Sound is 45° to the right (50% volume on the left)
100: Sound is all the way to the right
=> Implement positional audio in adpcm

iop/sound/audsrv/src/adpcm.c
I was getting strange issues where sounds where being replaced. Turns out that if you load memory past the end of the 2MB available memory it will just wraparound and load sounds on top of each other. This now returns an OOM error instead.
=> Return an error when out of SPU memory

ee/rpc/audsrv/include/audsrv.h, ee/rpc/audsrv/src/audsrv_rpc.c, ee/rpc/audsrv/src/audsrv_rpc.h, iop/sound/audsrv/include/audsrv.h, iop/sound/audsrv/src/adpcm.c, iop/sound/audsrv/src/rpc_server.c
Remove an adpcm sample uploaded with audsrv_load_adpcm() from the list of loaded sounds.
This allows games to free up SPU memeory by removing the latest loaded sounds from the list. For efficient managment commonly used sounds should be loaded first so that they do not need to be unloaded to free up memory.
=> Implement audsrv_free_adpcm

ee/rpc/audsrv/include/audsrv.h, ee/rpc/audsrv/samples/playadpcm/playadpcm.c, iop/sound/audsrv/src/adpcm.c
Returning the assigned channel lets us control the volume and other properties while using dynamically assigned channels.
=> Return channel id when sample is successufully started

ee/rpc/audsrv/include/audsrv.h, ee/rpc/audsrv/src/audsrv_rpc.c, ee/rpc/audsrv/src/audsrv_rpc.h, iop/sound/audsrv/include/audsrv.h, iop/sound/audsrv/src/adpcm.c, iop/sound/audsrv/src/rpc_server.c
This lets you check if your sample is still playing on the given channel
=> Implement audsrv_is_adpcm_playing

iop/fs/bdmfs_fatfs/src/fs_driver.c
`offset` was subtracted but where it should have been added instead
=> bdmfs_fatfs: Fix SEEK_END

iop/sio/mx4sio_bd/src/mx4sio.c, iop/sio/mx4sio_bd/src/spi_sdcard_driver.c
```
if (spi_ss == 0) {
// We're ignoring a lot of dummy read/writes, this is not an error
// M_DEBUG("%s(%d) - ignoring, not selected\n", __FUNCTION__, byte);
return 0;
}
```
This check renders every instance of the following useless:
```
in spi_sdcard_driver.c:
_io->wr_rd_byte(DUMMY_BYTE);
_io->select();
_io->relese();
_io->wr_rd_byte(DUMMY_BYTE);
```  
As a result the clock is not toggled when it should be and this leads to issues with SanDisk sdcards. I'm not sure if this check was a means of optimization or an oversight. I haven't done any performance testing beyond loading up Half-Life with OPL, which seems okay. 
I've tested this fix with a 128GB SanDisk SDXC and a 16GB no brand SDHC, both seem to be fully working. Previously the 16GB would only be detected and wasnt able to get far …
=> fix for sandisk sdcards

iop/fs/bdmfs_fatfs/src/fs_driver.c
The description of this changed parameter:
`Mount option: 0=Do not mount (delayed mount), 1=Mount immediately`
Setting this to 0 will always return succes, even if the filesystem is not supported. We need to "mount immediately" so we can report back to BDM if this is a supported filesystem, or not.
This also solves an issue in OPL when you have 2 partitions:
- the first being an usupported partition (like ntfs, ext4, etc...) - that would falsely be mounted as "mass0"
- the second being the partition with games - that would not show up
@grimdoomer do you agree on this PR, or do you have other things in the works that solve the same issue?
=> FatFS: Mount immediately so we can return ok/error

samples/Makefile.eeglobal_sample
Allow developers to change source files location and object files output location without copy pasting recipes. just declaring the `EE_*_DIR` variables
=> [EE Makefile]: imitate IOP Makefiles

ee/rpc/filexio/src/fileXio_rpc.c
This PRs has been created for solving #425 .
The problem was that after integrating newlib we created a bunch of pointer functions, to be able to support `fileXio` and `fio`:
https://github.com/ps2dev/ps2sdk/blob/master/ee/libcglue/include/ps2sdkapi.h#L20-L39
These functions by default are pointing to `fio`, however after loading `fileXio` irxs and calling to `fileXioInit();` all these functions are then pointing to `fileXio`. 
If we decide to `reset_IOP` we need to assure that we are pointing back these pointer functions to the original ones from `fio` otherwise, it will try to call some `fileXio` functions from IOP which aren't loaded anymore, having a beautiful frozen app.
The solution has been to keep a backup of the previous reference of the pointer functions, restoring them when …
=> Be sure we restore pointer glue I/O functions when deinit flieXio

samples/Makefile.eeglobal_sample
Reverts ps2dev/ps2sdk#421
Because it is making `ps2sdk-ports` to not compile, some `makefile` over there needs to be updated.
@israpps is already working on it, he will create the PR back, when the other PRs from `ps2sdk-ports` were ready.
Cheers.
=> Revert "[EE Makefile]: imitate IOP Makefiles"

ee/math3d/src/math3d.c
On the PS2, the clip flag is pipelined, and takes approximately 3-4 cycles to complete after a `vclipw`. This pull request adds 4 `vnops` after `vclipw` in the `calculate_vertices` function to allow time for the flag to properly update. This should fix the broken clipping seen in `cube.elf`.
=> Added some vnops to allow time for the clip flags to update in calculate_vertices

iop/system/threadman/src/thbase.c
obj_count shouldn't increment when skipping the idle thread
=> threadman: fix GetThreadmanIdList bug

ee/libcglue/Makefile, ee/libcglue/src/lock.c
After some conversion in #430 , we have figured it out that if we want to support a full multithreading I/O operations we need to provide a `lock API` implementation in PS2 to newlib.
This PR will require first to be merged https://github.com/ps2dev/ps2toolchain-ee/pull/29
Cheers
=> Added lockAPI

iop/dev9/ata_bd/Makefile, iop/dev9/atad/src/ps2atad.c
In this PR:
[Fix module name: ata_bd.irx](https://github.com/ps2dev/ps2sdk/commit/2ef60c59d1244ca85dbe2590de2e6ab4f5dffaeb)
[Initialize the HDD's so they can connect to BDM](https://github.com/ps2dev/ps2sdk/commit/4c5e750057d3fd6d02cc35e6f536c7c5d5f3f79a)
=> Fixes for ATA BDM

iop/system/iomanx/src/iomanX.c
Mainly for targeting non-IOP platforms
=> iomanX portability changes

iop/fs/bdmfs_fatfs/src/fs_driver.c
This is mainly to catch a potential bug where the file can disappear.
=> bdmfs_fatfs: do not rename if old and new path are same

iop/dev9/atad/src/ps2atad.c
Do not call proprietary SCE commands on this model as this will lock the hdd.
=> ATAD: fix for Crucial BX500 SSD

iop/fs/libbdm/include/bd_defrag.h, iop/fs/libbdm/src/bd_defrag.c
Add defragmentation write support. This can be used for emulating a memory card (VMC), or a HDD, in neutrino/OPL.
=> Add defragmentation write support

ee/kernel/include/timer_alarm.h
=> timer: Fix TimerBusClock2USec

ee/libcglue/Makefile, ee/libcglue/include/ps2sdkapi.h, ee/libcglue/samples/rewinddir/Makefile, ee/libcglue/samples/rewinddir/Makefile.sample, ee/libcglue/samples/rewinddir/main.c, ee/libcglue/src/fdman.c, ee/libcglue/src/fdman.h, ee/libcglue/src/glue.c, ee/libcglue/src/init.c, ee/libcglue/src/ps2sdkapi.c, ee/rpc/filexio/src/fileXio_rpc.c, samples/Makefile_sample
The main scope of this PR is to remove several helpers we created for open/close dir and use better what's it is provided by newlib.
It will also bring the usage of other functions such as `rewinddir` and some others.
This PR requires to be merged first: https://github.com/ps2dev/newlib/pull/8
The implementation of this PR follows the same approach that PSP did.
I have created an example to check that `readdir` keeps working, however could be nice to test some other examples.
I will try to add more examples later
As a summary the new functions being used from `newlib` are (they belong to the flag `HAVE_OPENDIR`):
- `closedir` https://man7.org/linux/man-pages/man3/closedir.3.html
- `dirfd` https://man7.org/linux/man-pages/man3/dirfd.3.html
- `ftw` …
=> Using more functionality from newlib and clean-up

ee/libcglue/Makefile, ee/libcglue/samples/regress/runner.c, ee/libcglue/samples/regress/stdio_tests.c, ee/libcglue/src/glue.c
This PR is to improve the usage of relative paths in all the POSIX functions. The same approach is also used by PSP.
More tests have been added to the regress sample
The remove file function has also been fixed, as newlib is using `_unlink` when removing a file.
Cheers.
=> Apply normalized to all functions

ee/libcglue/Makefile, ee/libcglue/src/cwd.c, ee/libcglue/src/glue.c, ee/libcglue/src/init.c
This PR improves the method that transforms the relative path into absolute paths, something needs to support POSIX functions with relative paths.
Specific content for `cwd` and paths has been moved to a separate file.
The returned error for several functions has been improved.
Once again the base code has been taken from the PSPSDK.
Cheers.
=> Fix relative paths

ee/libcglue/Makefile, ee/libcglue/include/ps2sdkapi.h, ee/libcglue/src/glue.c
With the new way of providing more POSIX functions, the FD that we provide to the final user is not the same as the FD given by the IOP driver, however, there are still some functions that aren't POSIX and we still need to call them directly sending the IOP's FD as `fileXioIoctl` and `fileXioIoctl2`.
This PR basically exposes a function to get the IOP FD.
Cheers.
=> Expose func to get IOP FD

ee/Rules.make, iop/Rules.make, samples/Makefile.eeglobal_cpp_sample, samples/Makefile.eeglobal_sample, samples/Makefile.iopglobal_sample
Allows `addr2line` to output line number and file path.
Will increase size of libraries and unstripped executables, but stripped and compressed executables should remain same size
=> Include compressed DWARF2 debug info by default for EE and IOP buildsystem

ee/libcglue/src/fdman.h
I think that 64 is a good number, if it is not enough, we can increase it later
=> Reducing FILENO_MAX to save static RAM space

ee/libcglue/src/glue.c
Update lseek64 implementation after new fd approach. It fixes: https://github.com/ps2homebrew/Open-PS2-Loader/issues/1129
=> Fix lseek64

ee/font/samples/font.c, ee/kernel/Makefile, ee/kernel/include/osd_config.h, ee/kernel/include/rom0_info.h, ee/kernel/src/osd_config.c, ee/kernel/src/rom0_info.c, ee/kernel/src/timer_alarm.c, ee/libcglue/Makefile, ee/libcglue/include/file-advanced.h, ee/libcglue/include/ps2sdkapi.h, ee/libcglue/samples/timezone/Makefile, ee/libcglue/samples/timezone/Makefile.sample, ee/libcglue/samples/timezone/main.c, ee/libcglue/src/glue.c, ee/libcglue/src/ps2sdkapi.c, ee/libcglue/src/timezone.c, ee/rpc/filexio/Makefile, ee/rpc/filexio/include/fileXio_rpc.h, ee/rpc/filexio/samples/Makefile, ee/rpc/filexio/samples/Makefile.sample, ee/rpc/filexio/samples/main.c, ee/rpc/filexio/src/fileXio_ps2sdk.c, ee/rpc/filexio/src/fileXio_rpc.c, samples/Makefile_sample
The main scope of this PR is to avoid having unused functions within the embedded ELF, unfortunately, the linker and compiler aren't that clever and require some help to make it work better.
More concretely most of the unused functions belong to the library used for performing IO operations, either `fileio` or `fileXio`. Having both in the binary first makes the a waste of space, and secondly could deal with problems if you start mixing by mistake `fd` from/to `fileio`/`filexio`.
How I did it:
- `rom0_info` contains some information about the `ROM0` included in the console, it was always using `fileio` for accessing the `ROM0` content, now, I have created a possibility to inject via driver the functions used to deal with IO operations.
- `osd_config` used functions from `rom0_info`, so …
=> Improve mixing usage `fileio` and `fileXio`

common/include/netinet/tcp.h
Required when compiling mongoose. Saved me having to patch it.
=> Add netinit/tcp.h

ee/kernel/include/rom0_info.h, ee/kernel/src/osd_config.c, ee/kernel/src/rom0_info.c, ee/libcglue/src/cwd.c, ee/libcglue/src/timezone.c
Thanks of the testing done by @israpps , I have faced 2 different issues when trying to do IO operation with `rom0`:
1. `rom0` can't have an `/`, and the previous code was always trying to put the `/` after the `:`, like `rom0:/ROMVER` which is wrong, now it properly does `rom0:ROMVER`
2. Additionally when using a custom IO driver for accessing roninfo.c functions, we were always hardcoding the usage of FIO flags, like `FIO_O_RDONLY`, so I added a new field to the `_io_driver` struct for saving the `openFlags`.
Not sure if there are other "units" different than `rom0` that should also skip the `/` after the `:`, please tell me if you are aware of any other drive.
Cheers.
=> Fix `rom0` access

ee/libcglue/src/cwd.c, ee/libcglue/src/glue.c
When normalized path, I'm checking if `drive` requires to have `/`, `\` or none for instance `mc0`, `cdrom` or `rom`
I have used the example done on OPL to check if it works as expected:
https://github.com/ps2homebrew/Open-PS2-Loader/blob/master/labs/opltestiso/ee/main.c
Cheers.
=> Fix usage of `CDROM` paths

ee/startup/src/linkfile
`.spad` section has been added for zero-initialized or uninitialized data to be located in scratchpad region.  
`.reginfo` and `.rodata` sections have been moved around.
=> EE linkfile changes

ee/libcglue/src/fdman.c
=> fix: libcglue/fdman use correct indices for stdout/stderr

Makefile, Rules.make, common/Makefile, common/external_deps/Makefile, tools/Rules.release
Mainly works around race conditions (regarding incomplete/corrupted files) by performing parallelism for a single directory at a time.
=> Buildsystem improvements 240117

ee/libcglue/src/ps2sdkapi.c, ee/rpc/filexio/src/fileXio_ps2sdk.c
Fixes fd being some large number (which is actually part of the file name)
=> When copying filename, use filename argument of file info

ee/kernel/src/sifrpc.c
This PR fixes a bug in SifRegisterRpc, where if the queue already had registered servers, the function would incorrectly iterate through the next field of the server linked list instead of the link field to find a free space for the server. With the old code, if an RPC request arrived for a queue with multiple registered servers, the SIFRPC protocol would execute not only the correct server, but all servers registered after it as well.
Practically speaking, this bug has little to no influence on current homebrew, as the vast majority of programs do not register any servers, let alone multiple ones to the same queue. However, the official SDK correctly handles this, so it is important that ps2sdk does as well.
=> EE SIFRPC: Fix bug in SifRegisterRpc

iop/startup/Makefile, iop/startup/src/crt0.c
In order to make it easier to use C++ on the IOP we can provide a crt0 with support for global constructors.
Is there anything else we should provide here? Or a reason to not provide it at all?
I know there would need to be additional things required to support threadsafe statics etc. But I'd be inclined to suggest just disabling anything that requires extra support. (i.e. building with  `-fno-exceptions -fno-rtti -fno-threadsafe-statics`)
=> [RFC/WIP] IOP: Provide crt0 with global constructor support

ee/elf-loader/src/loader/src/loader.c
This PR avoids the `_libcglue_args_parse` for saving space in the elf-loader.
Cheers
=> Disabling `_libcglue_args_parse` in `ELF Loader`

ee/kernel/src/timer.c
I still don't understand why we need this magic number, but reducing it, improves values.
Cheers
Following previous example:
```
Bigger diff: 29, requested: 9843, got: 9872
```
=> Improve timer accuracy

ee/startup/src/crt0.c
There was a severe issue where the bss segment was not properly being zeroed.
This caused major issues when using ps2link reset. IE: graph vram allocations not being reset, or `setenv` crashing after a soft reset. 
I originally thought these were two different issues, but newlib uses a static local variable to track if it has previously allocated https://github.com/ps2dev/newlib/blob/ee-v4.4.0/newlib/libc/stdlib/setenv_r.c#L56
Obviously, if you soft reset the system without marking this flag as zero, the next time it tries to use this no-longer-allocated memory, you would get a crash.
TLDR: This fixes globals not being set to zero, which in turn fixes probably that bug you've been chasing for weeks.
=> crt0: Fix bss init routine

tools/bin2c/src/bin2c.c
Uses memory mapping for input and output files.
There wasn't much performance increase on using the input file mapping, but there was a large one for the output file.
I optimized further by going away with `sprintf` for every byte (or every 16 bytes when unrolled) and incorporated a simple LUT. The `memcpy` is optimized by gcc/clang to around 7 instructions.
Here are some benchmarks tested on files generated with /dev/urandom:
(Any lower than 100kB has no measurable difference)
```
100 kB file
master:
real	0m0.007s
user	0m0.007s
sys	0m0.000s
pr:
real	0m0.003s
user	0m0.000s
sys	0m0.001s
1.0 MB file
master:
real	0m0.064s
user	0m0.060s
sys	0m0.004s
pr:
real	0m0.009s
user	0m0.000s
sys	0m0.005s
10 MB file
master:
real	0m0.602s
user	0m0.567s
sys	0m0.033s
pr:
real	0m0.086s
user	0m0.010s
sys …
```
=> bin2c: Optimize with memory mapping and a LUT

ee/kernel/include/kernel.h
Makes using GetCop0 and SetCop0 easier
`ee_cop0_defs.h` exists, but the defines are intended to be used in assembly, rather than passed as an argument.
=> kernel: Add COP0 register enum

common/include/iop_regs.h
This allows us to detect DECKARD models without even opening `rom0:DECKARD`. Thought it might be useful to have it as part of the SDK headers
=> add IOP type checker macros

ee/startup/src/crt0.c
The registers assigned to constraints and the manually selected ones conflicted resulting in the bss loop trampling them.
Properly labeling clobbers and smarter constraint use should fix this.
=> Fix crt0 inline asm

tools/ps2-irxgen/Makefile, tools/romimg/src/SonyRX.c, tools/romimg/src/main.c, tools/romimg/src/platform.c, tools/romimg/src/romimg.c
The rooming tool is not compiling for the MacOS environment.
Please check that things still compile for Linux and Windows environments
@rickgaiser and @israpps 
Cheers.
=> Fixing MacOS compilation

.github/workflows/compilation.yml
Allows to recompile SDK without commiting to the branch. Also allows forks to run workflow on other branches without commiting to main branch
=> Allow manual workflow execution

iop/fs/filexio-verbose/Makefile, iop/fs/filexio/src/fileXio_iop.c
Useful if developer wants to track open,close,read,etc,etc while debugging without having to clone and compile PS2SDK again nor store prebuilt copy on repository.
Will also help a lot to see how path changes when passing through the libcglue path normalization
=> include debug fileXio on SDK distribution

tools/romimg/src/main.c, tools/romimg/src/platform.h, tools/romimg/src/romimg.c
With this commit:
```bash
bin/romimg -c IOPRP.IMG $HOME/SECRMAN $HOME/SECRSIF
```
Results in these contents:
```
PlayStation 2 ROM image generator v1.12
Compiled on Mar 21 2024 - 17:57:57
---------------------------------------
ROM datestamp:  2024/03/21
ROM comment:    20240321,conffile,IOPRP.IMG,isra@DESKTOP-AO7864M//mnt/c/Users/tatoc/OneDrive/Documentos/ps2sdk/tools/romimg
File list:
Name            Size
-----------------------------
RESET           0
SECRMAN         18444
SECRSIF         4548
```
before the result would have been:
```
PlayStation 2 ROM image generator v1.12
Compiled on Mar 21 2024 - 17:57:57
---------------------------------------
ROM datestamp:  2024/03/21
ROM comment:    20240321,conffile,IOPRP.IMG,isra@DESKTOP-AO7864M//mnt/c/Users/tatoc/OneDrive/Documentos/ps2sdk/to …
```
=> allow romimg to access files from absolute paths

.github/workflows/tools.yml, Makefile, tools/romimg/src/main.c
This PR adds the compilation of tools in the available supported systems Linux, Windows, and MacOS.
In this way now we can check if we merge something that is breaking the CI, previously, we didn't face any error till by dispatching it reached the `ps2dev` repo.
Cheers
=> Adding tools to CI/CD

tools/bin2c/src/bin2c.c
Fixes a regression for the MSYS2 platform from #538 
For whatever reason, mman support for MSYS2 was refused and they've been mman-less ever since.
I kept the LUT for the MSYS2 platform, but fell back to the generic posix read/write functions for IO. There's memory mapping support through the win32 api, but I don't it's worth implementing for this (hopefully-soon-to-be-abandoned) platform.
Also, I don't know why the formatting changed. I've run the file through clang-format.
=> bin2c: Support mman/mmap-less platforms (MSYS2)

ee/libcglue/Makefile, ee/libcglue/src/glue.c
This PR basically makes the `std::filesystem::directory_iterator` work as expected.
I have used this example:
```cpp
#include <stdio.h>
#include <filesystem>
int main(void)
{
std::filesystem::directory_iterator dir_scanner("./");
for (auto &entry : dir_scanner) {
printf("%s\n", entry.path().string().c_str());
}
return 0;
}
```
It prints content of folder:
```
[    9.2121] dopen name host:/Users/fjtrujy/Downloads/filesystem-test-48641ffa 
[    9.2127] dopen fd = 256
[    9.2180] read/write allocate memory 4000
[    9.2182] ./CMakeFiles
[    9.2183] ./Makefile
[    9.2186] ./cmake_install.cmake
[    9.2231] ./filesystem-test.elf
[    9.2233] ./CMakeCache.txt
```
Cheers.
=> Add `F_SETFD` cmd to `_fcntl` function

ee/kernel/src/kernel_util.c, ee/libpthreadglue/src/osal.c
Now all the test from `pthread-embedded` are passing correctly:
```
[    1.7781] Running tests...
[    1.7784] =========================
[    1.7788]    Test iteration #0
[    1.7791] =========================
[    1.7792] Reuse test #1
[    1.7836] Create test #1
[    3.7540] Create test #2
[    3.7699] Create test #3
[    3.7710] Join test #0
[    5.7705] Join test #1
[    7.8229] Join test #2
[    9.8225] Join test #3
[   10.8258] Join test #4
[   15.8258] Kill test #1
[   15.8261] Exit test #1
[   16.8247] Exit test #2
[   17.8255] Exit test #3
[   18.8262] Priority test #1
[   18.8271] Priority test #2
[   18.8408] Valid test #1
[   18.8417] Valid test #2
[   18.8418] Self test #1
[   18.8419] Self test #2
[   18.9422] Equal test #1
[   20.9421] Count test #1
[   21.9430] Delay test …
```
=> Fix pthread

ee/libcglue/samples/nanosleep/main.c, ee/libcglue/src/glue.c, ee/libpthreadglue/src/osal.c, ee/network/tcpip/src/sys_arch.c
After fixing the implementation of `clock()`, now it returns values in `microseconds`, so now we need to make some adjustments.
Before mergin this PR we need to merge first https://github.com/ps2dev/newlib/pull/12
=> Fix usage of `clock` and `CLOCKS_PER_SEC`

ee/libcglue/Makefile, ee/libcglue/src/init.c, ee/libcglue/src/lock.c
To have thread-safe operations for all the `newlib` operations we have been required to do several PR:
- [`newlib`](https://github.com/ps2dev/newlib/pull/13)
- [`ps2toolchain-ee`](https://github.com/ps2dev/ps2toolchain-ee/pull/44)
- [`ps2sdk`](https://github.com/ps2dev/ps2sdk/pull/592)
This PR fixes the implementation of lock API. The previous implementation never was used due to a miss config in the `ps2toolchain-ee`, and it was wrong.
=> Fixing lock API

.github/workflows/tools.yml
Finishes my incomplete PR #584
I forgot you guys always add the pull request trigger. Wich causes double execution of CI on pull request when paired with `push`
=> [tools] only run CI if PR changed tools dir

iop/fs/bdmfs_fatfs/Makefile, iop/fs/bdmfs_fatfs/src/diskio.c, iop/fs/bdmfs_fatfs/src/ff.c, iop/fs/bdmfs_fatfs/src/ffsystem.c, iop/fs/bdmfs_fatfs/src/include/ff.h, iop/fs/bdmfs_fatfs/src/include/ffconf.h
The main scope of this PR is to have better control over the changes we are doing over the FatFS dependency.
I have created this [FatFS repo](https://github.com/fjtrujy/FatFs) which basically contains one commit per release of FatFs done.
Additionally, I have created a separate branch, [`iop-r0.14b`](https://github.com/fjtrujy/FatFs/tree/iop-r0.14b) where I have applied current `ps2sdk` changes there to visually see better what are custom changes done by our needs in one single [commit](https://github.com/fjtrujy/FatFs/commit/7b11bf0552be728a809614f861773a9a294ef30f).
The majority of the changes that this PR has are related to code style (to match the original code), additionally some other tiny improvements have been done:
- All warnings have been solved and module `bdmfs_fatfs` now …
=> Cleaning up FatFS dependency

common/include/fileXio.h, ee/rpc/filexio/src/fileXio_rpc.c, iop/fs/filexio/src/fileXio_iop.c
When executing `fileXioWrite` we were using an extra buffer of 64 bytes for trying to solve 64 bytes alignment:
```
unsigned int unalignedDataLen;
unsigned char unalignedData[64];
```
Producing then 2 separate write calls, firstly for writing the `unalignedData` with `unalignedDataLen` and secondly for the remaining things.
This extra work is not needed at all as the un-alignement is going to be solved by the `SifRpcGetOtherData` call.
This PR is not fixing all the possible scenarios we can face with #594 , however it helps to mitigate the issue.
Cheers
=> Remove extra unaligned buffer as it solved using `sceSifGetOtherData`

common/include/fileXio.h, ee/rpc/filexio/src/fileXio_rpc.c, iop/fs/filexio/src/fileXio_iop.c
Reverting this PR because I have detected some scenarios where it fails
Reverts ps2dev/ps2sdk#604
=> Revert "Remove extra unaligned buffer as it solved using `sceSifGetOtherData`"

iop/dev9/atad/Makefile, iop/dev9/atad/src/ps2atad.c, iop/fs/bdm/Makefile, iop/fs/bdm/src/include/module_debug.h, iop/fs/bdm/src/part_driver.c, iop/fs/bdm/src/part_driver_gpt.c, iop/fs/bdmfs_fatfs/Makefile, iop/fs/bdmfs_fatfs/src/ff.c, iop/fs/bdmfs_fatfs/src/fs_driver.c, iop/fs/bdmfs_fatfs/src/include/module_debug.h, iop/fs/libbdm/Makefile, iop/fs/libbdm/src/bd_cache.c, iop/fs/libbdm/src/include/module_debug.h, iop/iLink/IEEE1394_bd/Makefile, iop/iLink/IEEE1394_bd/src/imports.lst, iop/iLink/IEEE1394_bd/src/include/module_debug.h, iop/iLink/IEEE1394_bd/src/scsi.c, iop/sio/mx4sio_bd/Makefile, iop/sio/mx4sio_bd/src/module_debug.h, iop/usb/usbmass_bd/Makefile, iop/usb/usbmass_bd/src/include/module_debug.h, iop/usb/usbmass_bd/src/scsi.c
This PR is just to change how the macro `U64_2X32` was done. 
We were forced to disable `Wno-strict-aliasing` warning, with this new approach is not needed anymore.
Cheers.
=> Improve macro `U64_2XU32`

iop/memorycard/mcman/src/main.c
Avoids FreePSXBoot-prepared memorycards from causing memory corruption
=> fix: [mcman] add bounds checks for linked_block member of PS1 mcfs

ee/input/src/input.c
Ran into an error for this when building with gcc14. It looks like the right thing to do.
=> input: Fix uninitialized use.

ee/libcglue/Makefile, ee/libcglue/include/netdb.h, ee/libcglue/include/ps2sdkapi.h, ee/libcglue/include/sys/socket.h, ee/libcglue/src/netdb.c, ee/libcglue/src/socket.c, ee/network/tcpip/src/ps2ip_ps2sdk.c, ee/rpc/tcpips/src/ps2ipc_ps2sdk.c
In this PR we are adding dummy implementation for IOP and EE driver for:
- `gethostbyaddr`
- `sndmsg`
- `recvmsg`
=> Add dummy implementation for some missing net functions

.github/workflows/compilation.yml
The previous implementation didn't work well if you moved to a different folder.
=> Using relative path for the symbolic links

samples/ps2dev.cmake, samples/ps2dev_iop.cmake
- this allows to build libpng correctly without error of mismatching zlib version
=> build: assigned include dirs and lib dirs the correct way

tools/romimg/src/ELF.h, tools/romimg/src/SonyRX.c, tools/romimg/src/SonyRX.h, tools/romimg/src/platform.h, tools/romimg/src/romimg.h
This PR basically removes the usage of nonstandard types in the tools directory.
Some additional improvements on the headers files have been made.
@israpps this tool was added by you
=> Stop using `u8`, `u16` and `u32` in the roming tool

ee/startup/src/crt0.c
The current implementation of `crt0.c` looks to be wrong as we are calling `_InitSys()` too late.
Within `_InitSys()` we are initialization timers, alarms, and some others.
In the existing implementation, we are calling `_InitSys()` after calling `libcglue_init` and the C++ constructors; this mean we couldn't use for instance timers on those specific functions.
This is why I think that `_InitSys` should be called way earlier, as it doesn't have any `newlib` requirement.
Cheers.
=> Call `_InitSys()` before newlib initialization

.github/workflows/compilation.yml, Dockerfile, ee/libcglue/Makefile, ee/libcglue/src/init.c, ee/libprofglue/Makefile, ee/libprofglue/src/mcount.S, ee/libprofglue/src/prof.c
This PR brings us the option to measure our code in order to find out possible bottlenecks.
In order to make this to work there are 2 previous PRs that need to be merged:
- Enable `gprof` binary compilation from newlib: https://github.com/ps2dev/binutils-gdb/pull/5
- Add `libprofglue` as part of the standard libraries when using the flags `-pg` https://github.com/ps2dev/gcc/pull/11
The current implementation being used here is inspired by the existing implementation for PSP.
https://github.com/pspdev/pspsdk/tree/master/src/prof
Basically, you need to compile your code using the `-pg -g` flags for compilation and linking.
Then **when exiting your app**, it will automatically generate a file called `gmon.out`. In order to interpret that file you require to use the `gprof` tool.
More info: …
=> Implementing profglue

samples/ps2dev.cmake, samples/ps2dev_iop.cmake
This pr is for fixing smb2man.irx library.
=> [PS2 libretro]: Add cmake minimum dependency.

ee/elf-loader/src/loader/linkfile
This PR is to update the `linkfile` used on the `elf-loader`.
The current `linkfile` doesn't work properly if we need to use heap memory.
In theory current `elf-loader` doesn't use Heap, however, it uses some functions from `newlib` so we can't easily guess if it is using internally `heap` or not, so let's update & fix the `linkfile` anyway.
More info here: https://github.com/ps2dev/ps2link/pull/56
Cheers.
=> Update `elf-loader` `linkfile`

tools/bin2c/src/bin2c.c
Putting back the previous `bin2c` implementation as the current one looks to produce wrong information in the Window MSYS environment
=> Use legacy bin2c

iop/security/secrman/src/MechaAuth.c, iop/security/secrman/src/MechaAuth.h, iop/security/secrman/src/secrman.c
these functions retrieve the kbit and kc, after they were decrypted and encrypted with session key on the mechacon, after being sent via secrdownloadheader
=> [SECRMAN] rename funcs related to kbit/kc obtainment

samples/Makefile, samples/Makefile.eeglobal_sample, samples/Makefile.ioprp_sample, tools/romimg/src/main.c, tools/romimg/src/platform.c, tools/romimg/src/platform.h, tools/romimg/src/romimg.c, tools/romimg/src/romimg.h
instead of relying on strlen, go straight away with max bufsize. before this change the romimg from docker would segfault while local build works like a charm
New feature, `-c` and `-a` commands will have new variants, `-C` and `-A`, these will manipulate the filename written to ROMFS removing extension and converting to uppercase
So for example
```bash
romimg -C IOPRP.IMG $PS2SDK/iop/irx/secrman.irx
```
Will register secrman.irx as `SECRMAN` on the image, this seems to be needed when the IOPRP is replacing startup IOP modules
=> fix romimg bundled on docker containers

iop/system/iomanx/src/iomanX.c
Matches previous behavior. Is important in the case of passing `0` in flags
=> iomanX use device instead of mode for allocation check

ee/libcglue/Makefile, ee/libcglue/include/sys/termios.h, ee/libcglue/include/sys/uio.h, ee/libcglue/include/sys/utime.h, ee/libcglue/src/glue.c
`sys/termios.h`, `sys/uio.h`, and `sys/utime.h` were adapted from newlib cygwin port  
`readv` and `writev` were implemented  
Document where functions are called from in newlib
This gets libarchive mostly building with minimal  patches (2 lines)
=> Implement more functions in libcglue 20241204

ee/libcglue/Makefile, ee/libcglue/src/glue.c, ee/libcglue/src/ps2sdkapi.c, ee/rpc/filexio/src/fileXio_ps2sdk.c
Currently, ioctl calls are failing, as `__fioOpsInitializeImpl` and `__fileXioOpsInitializeImpl` are checking for the wrong symbol when setting operation handlers.
Offending lines:
https://github.com/ps2dev/ps2sdk/blob/69f54b9f923db871ea1582a62c9db8866a017fe5/ee/libcglue/src/ps2sdkapi.c#L489
https://github.com/ps2dev/ps2sdk/blob/69f54b9f923db871ea1582a62c9db8866a017fe5/ee/rpc/filexio/src/fileXio_ps2sdk.c#L506
`_ioctl` is not defined anywhere, thus `x_ops_file.ioctl` will remain as `NULL`. This in turn will result in an ENOSYS in `_ps2sdk_ioctl`. The correct symbol to check here would be `_ps2sdk_ioctl`. I corrected the error, and defined `_ioctl` in `glue.c` for consistency.
Tested and validated via PCSX2 emulator.
=> fix ioctl failing with ENOSYS.

iop/cdvd/cdfs/src/cdfs_iop.c, iop/cdvd/cdfs/src/cdfs_iop.h, iop/cdvd/cdfs/src/main.c
Reducing the number of max folders and max files that can be opened at the same time in the CDFS driver.
This drastically reduces the amount of RAM wasted on this driver.
I plan to do a further refactor in the following PRs, but this is a a quick win for now.
Before:
```
================== RAM ====================
Symbol                   Size        %
===========================================
?                        613.1 KiB   100.00
fod_table              584.2 KiB    95.28
local_buffer.1          18.0 KiB     2.94
dvdvBuffer               2.0 KiB     0.33
cdVolDesc                2.0 KiB     0.33
localVolDesc.1           2.0 KiB     0.33
cacheInfoDir             1.0 KiB     0.17
pathcopy.3               1.0 KiB     0.16
pathname.5               1.0 KiB     0.16
dirname.2 …
```
=> Reduce cdfs ram

ee/kernel/src/iopheap.c
It is redundant. It may be a typo on the version variable, but we don't need to check version in that case
Closes #434
=> cleanup: remove unneeded memset in SifExitIopHeap

ee/kernel/src/sifrpc.c
This PR solves an issue when `SifSendCmd` fails and the Semaphore wasn't being deleted.
Additionally, I'm now deleting the semaphore in case of success in the `_request_end` callback function, which simplifies the logic a bit.
Cheers
=> Delete semaphore on E_SIF_PKT_SEND error

iop/system/padman/src/imports.lst, iop/system/padman/src/padData.c
This works around the backwards compat potential hang
=> fix: use sio2_pad_transfer_init2 for xfer init with mtap

ee/kernel/src/timer.c, ee/libcglue/samples/nanosleep/main.c, ee/libcglue/src/glue.c, ee/libcglue/src/sleep.c
This PR fixes an existing issue #530.
The existing timer implementation was working almost right, the real issue was in the `_times`'s implementation in `libcglue` that was losing too much precision.
Additional changes have been made too:
- Use `TimerBusClock2USec` for returning proper `usecs` in the `_times` function
- Improve `errno` logic in the `nanosleep` function.
- Improve the accuracy of the timer by reducing the GAP after the immediate equal interruption.
- Improve variable names and comments in the timer.
- Put back the error tolerance in the nanosleep example to `5ms` as it was originally.
Additionally, I have also tested implementation with the  program described here: https://github.com/ps2dev/ps2sdk/issues/527#issue-2132778883
```
Bigger diff: 24, requested: 9145, got: 9169 …
```
=> Fix timer accuracy

ee/kernel/Makefile, ee/kernel/include/kernel.h, ee/kernel/include/syscallnr.h, ee/kernel/src/kernel.S, ee/libcglue/samples/mem_test/main.c
This mainly avoids a fileio call at init
=> SetMemoryMode syscall related changes

iop/hdd/apa/src/hdd.c
This PR adds a check before `apaJournalRestore` to avoid corrupting non-APA HDDs during ps2hdd initialization.
Fixes #726.
=> [ps2hdd] Do not restore journal on unformatted HDDs to avoid corrupting non-APA HDDs

ee/libcglue/src/glue.c
=> Return an error for `fsync` as it is not implemented

tools/srxfixup/src/srxgen.c
It seemed like a pretty confusing limitation, so it's probably good to explain why.
=> srxfixup: explain IOP max alignment errors

ee/kernel/Makefile, ee/kernel/include/kernel.h, ee/kernel/include/timer.h, ee/kernel/src/initsys.c, ee/kernel/src/timer.c, ee/libcglue/Makefile, ee/libcglue/include/ps2sdkapi.h, ee/libcglue/src/glue.c, ee/libcglue/src/rtc.c, ee/libcglue/src/timezone.c
Allows smaller executables when not using those functions.
Nanosleep and timezone samples continue to function.
=> Link timer, timezone, and RTC functions only if they are used

iop/sound/libsd/src/libsd.c
I was seeing some strange behaviour when ADPCM voice samples were being uploaded past a certain address.
It seems that the Transfer Start Address was being truncated to 16 bits when it should be 20. This adds the extra 4 bits to the TSAH register, meaning that the full 2MB is now addressable (in 16 bit units). As far as I can tell, this fixes the problem.
=> Fix SPU2 DMA address calculation

ee/erl/src/erl.c
This is an improvement for the last ERL lower bits address compensation. Now it checks for a redundancy that could lead apply_reloc to add 1 for an already fixed address.
=> fix: remove lower bit add redundancy

ee/graph/include/graph.h, ee/graph/src/graph.c
Specify argument type of function ptr, empty args will be equavalent to `(void)` in future C standards. Fixes a GCC15 error.
=> graph: fix callback function ptr

iop/deckard/Makefile, iop/deckard/xparam/Makefile, iop/deckard/xparam/include/xparam.h, iop/deckard/xparam/src/database_0220_20050620.c.c, iop/deckard/xparam/src/database_0250_20100415.c, iop/deckard/xparam/src/database_merged.c, iop/deckard/xparam/src/imports.lst, iop/deckard/xparam/src/irx_imports.h, iop/deckard/xparam/src/xparam.c
A homebrew XPARAM module. with a simplified database parsing routine.
This is more of a "historical preservation" than actual utility.
of course it's up to you to merge it or not. But I thought it was worth it to have here
=> add xparam module

iop/fs/bdm/src/part_driver_mbr.c
Latest bdm exFAT drivers fail on some FAT32 drivers. Looks like bdm has forgot to add support for VBR.
On invalid MBR records it is trying to mount invalid partitions. This restores that functionality. Many of the such devices are formatted this way to bypass FAT32 max limit of 32GB in Windows. 
Alternatively someone needs to add better support for VBR. Sometimes a VBR can be valid and not even have MBR signature in the end of first sector. For now this will do.
The original authors of bdm are welcomed to give their insight.
resolves DKWDRV/DKWDRV#82
Possible impacts OPL since a long time already?
resolves ps2homebrew/Open-PS2-Loader#1311
resolves ps2homebrew/Open-PS2-Loader#1295
resolves ps2homebrew/Open-PS2-Loader#1271
resolves ps2homebrew/Open-PS2-Loader#1493
=> bdm MBR add support for VBR

samples/ps2dev.cmake, samples/ps2dev_iop.cmake
Fixes usage with newer cmake that dropped support for older versions compatibility
=> Specify minimum policy version for CMake backwards compatibility

ee/mpeg/Makefile, ee/mpeg/samples/mpeg.c, ee/mpeg/src/libmpeg_core.s
This PR fixes libmpeg and it's sample code.
Change registers to N32 ABI standards.
Fix $at usage, changing it for $t8 and/or using "use no/at".
Fix sample code primitive offset values.
Restore Assembly source compilation, since the C source doesn't work yet.
=> fix: restore libmpeg

iop/iLink/IEEE1394_bd/src/include/scsi.h, iop/iLink/IEEE1394_bd/src/sbp2_driver.c, iop/iLink/IEEE1394_bd/src/scsi.c, iop/sio/mx4sio_bd/src/spi_sdcard_driver.c, iop/usb/usbmass_bd/src/imports.lst, iop/usb/usbmass_bd/src/include/scsi.h, iop/usb/usbmass_bd/src/scsi.c, iop/usb/usbmass_bd/src/usb_mass.c
This PR fixes the use of the block_device `devNr` field. Whenever possible the `devNr` should hold a value that is persistent across reboots.
- **ATA**: master=0, slave=1 (was already implemented)
- **USB**: 0=first port, 1=second port, 2=hub, fixed in this PR
- **MX4SIO**: 1=second port, fixed in this PR
- **IEEE1394**: not implemented (incrementing number)
- **UDPBD**: not implemented (incrementing number)
The already existing ioctl can be used to query this device number:
https://github.com/ps2dev/ps2sdk/blob/88fdeb04289a0bf5c3dbf1e9ebfcd825cd82105f/common/include/usbhdfsd-common.h#L38-L39
@DKWDRV I have put this code together for you, to end the dicussion in https://github.com/ps2dev/ps2sdk/pull/757. I only compile tested it. Please check [this …
=> Use BDM bd.devNr for port numbers

iop/cdvd/cdvdman/src/cdvdman.c, iop/cdvd/cdvdstm/src/cdvdstm.c, iop/debug/iop_sbusdbg/src/main.c, iop/debug/iop_sbusdbg/src/sbus_tty.c, iop/debug/ppctty/src/tty.c, iop/debug/sior/src/xprintf.c, iop/dev9/poweroff/src/poweroff.c, iop/fs/netfs/src/ps2_fio.c, iop/memorycard/mcserv/src/mcserv.c, iop/network/spduart/src/spduart.c, iop/sound/ahx/src/ahx_irx.c, iop/sound/audsrv/src/audsrv.c, iop/sound/audsrv/src/common.c, iop/sound/audsrv/src/common.h, iop/sound/ps2snd/Makefile, iop/sound/ps2snd/src/ps2snd.c, iop/system/modload/src/modload.c, iop/system/mtapman/src/freemtap.c, iop/system/mtapman/src/rpcservers.c, iop/system/sifman/src/sifman.c, iop/system/sysclib/src/embeddedartistry_libc/stdlib/strtol.c, iop/system/sysclib/src/embeddedartistry_libc/stdlib/strtoul.c
The majority of the changes were just wrong pointer types.
Is good GCC is forcing us to be more strict with this kind of thing.
Cheers
=> Apply needed fixes for GCC 15.1

ee/erl/include/hashtab.h, ee/erl/include/lookupa.h, ee/erl/include/recycle.h, ee/erl/include/standard.h, ee/erl/src/erl.c, ee/erl/src/hashtab.c, ee/erl/src/lookupa.c, ee/erl/src/recycle.c, ee/rpc/ps2snd/Makefile, tools/gensymtab/Makefile, tools/ps2adpcm/Makefile
This PR basically does the needed changes for making the repo to compile with GCC 15.
Some other improvements has been done:
- Fixing compilation by removing legacy function definition style
- Remove the unnecessary custom typedef
- Improve header definitions
- Some other small changes
- Remove the `-std=c99` from the makefile.
Cheers
=> Prepare for GCC 15 upgrade

ee/kernel/include/delaythread.h
=> kernel: Fix c++ support for DelayThread

iop/hdd/apa/src/apa-opt.h, iop/hdd/apa/src/hdd.c, iop/hdd/apa/src/hdd_fio.c, iop/hdd/hdck/src/hdck.c, iop/hdd/hdsk/src/sim.c, iop/hdd/libapa/src/apa.c, iop/hdd/libapa/src/free.c
This PR introduces the following changes:
- Reduces the minimum APA partition size from 128 MB to 8 MB.
- Fixes an issue where `__empty` partitions could exceed APA spec limits — they are now restricted to a maximum of 1 GB.
- Enhances `getStat()` to report the total partition size (main + all sub-partitions) using the `private_1` and `private_2` fields.
=> Support for 8MB APA Partitions, getStat Enhancements, apaRemove per APA specs

iop/memorycard/mcman/src/mcsio2.c
Before this change, every time mcdetectcard was called from libmc over an unformatted card, the mcsync return value was -2
It should have been -2 if a new unformatted card was inserted since las call, and 0 if the same card remains plugged
fixes #785 
Only tested on emulator so far...
For refence, here you have other instances of this code:
Soulcalibur2 DONGLEMAN.IRX:
```c
int mcman_probePS2Card(int param_1,int param_2)
{
undefined4 uVar1;
int r;
int iVar2;
WaitSema(sema_hakama);
mcman_55_retval = 0xff;
r = mcman_cardchanged(param_1,param_2);
if ((r == 0) && (r = McGetFormat(param_1,param_2), r != 0)) {
if (param_1 == 0) {
uVar1 = mcman_getcnum(0,param_2);
SecrAuthDongle(2,param_2,uVar1);
}
SignalSema(sema_hakama);
r = 0;
} else {
...........
}
return r;
```
SCPH-50001/N `rom0:XMCMAN`: …
=> fix mcman detection of unformatted card insertion
